#!/bin/bash

root=`dirname $0`
lib="$root/compiler/target/lib"
comp="$root/compiler/target/compiler-1.0-SNAPSHOT.jar"

if [ -f "$comp" ]
then
	java -cp "$comp:$lib/core-1.0-SNAPSHOT.jar:$lib/javarag-0.0.1-SNAPSHOT.jar:$lib/jopt-simple-4.7.jar" se.lth.cs.tycho.compiler.Compiler "$@"
else
	echo "Tycho is not compiled. Please, run \"mvn install\" to compile Tycho."
	exit 1
fi