/* 
 *  @author Per Andersson<Per.Andersson@cs.lth.se>, Lund University
 *  To parse a CAL file use one of the methods:
 *  - public net.opendf.ir.cal.Actor parse(String path, String fileName)
 *  - public net.opendf.ir.cal.Actor parse(File file)
 *
 *  After parsing check for errors in the attribute parseProblems.
 *
 *  The parser is created using jflex and beaver.
 */
 
package net.opendf.parser.lth;

import java.util.ArrayList;
import net.opendf.ir.net.ast.PortReference;
import java.util.Map;
import net.opendf.ir.net.ast.NetworkDefinition;
import net.opendf.ir.net.ToolValueAttribute;
import net.opendf.ir.net.ToolTypeAttribute;
import net.opendf.ir.net.ast.EntityIfExpr;
import java.util.AbstractMap;
import java.io.PrintStream;
import net.opendf.ir.net.ToolAttribute;
import net.opendf.ir.net.ast.EntityListExpr;
import net.opendf.ir.net.ast.StructureStatement;
import java.util.TreeSet;
import beaver.*;
import net.opendf.ir.net.ast.StructureForeachStmt;
import java.util.Arrays;
import net.opendf.ir.net.ast.EntityInstanceExpr;
import net.opendf.ir.net.ast.StructureConnectionStmt;
import net.opendf.ir.common.*;
import net.opendf.ir.net.ast.StructureIfStmt;
import net.opendf.ir.net.ast.EntityExpr;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "NlParser.beaver".
 */
public class NlParser extends Parser {
	static public class Terminals {
		static public final short EOF = 0;
		static public final short NETWORK = 1;
		static public final short IDENTIFIER = 2;
		static public final short LPAREN = 3;
		static public final short RPAREN = 4;
		static public final short PORTCONN = 5;
		static public final short COLON = 6;
		static public final short IF = 7;
		static public final short THEN = 8;
		static public final short ELSE = 9;
		static public final short END = 10;
		static public final short IMPORT = 11;
		static public final short EQ = 12;
		static public final short SEMICOLON = 13;
		static public final short MAP = 14;
		static public final short LBRACE = 15;
		static public final short RBRACE = 16;
		static public final short BEGIN = 17;
		static public final short VAR = 18;
		static public final short DO = 19;
		static public final short CHOOSE = 20;
		static public final short IN = 21;
		static public final short COMMA = 22;
		static public final short LBRACK = 23;
		static public final short RBRACK = 24;
		static public final short DOT = 25;
		static public final short ALL = 26;
		static public final short EDGE = 27;
		static public final short DOUBLECOLON = 28;
		static public final short MUTABLE = 29;
		static public final short EQCOLON = 30;
		static public final short FUNCTION = 31;
		static public final short PROCEDURE = 32;
		static public final short MULTI = 33;
		static public final short OLD = 34;
		static public final short LET = 35;
		static public final short CONST = 36;
		static public final short LAMBDA = 37;
		static public final short COLONEQ = 38;
		static public final short WHILE = 39;
		static public final short ENTITIES = 40;
		static public final short STRUCTURE = 41;
		static public final short ENTITY = 42;
		static public final short ENDNETWORK = 43;
		static public final short LT = 44;
		static public final short ARROW = 45;
		static public final short BAR = 46;
		static public final short INTEGER_LITERAL = 47;
		static public final short LONG_LITERAL = 48;
		static public final short FLOATING_POINT_LITERAL = 49;
		static public final short DOUBLE_LITERAL = 50;
		static public final short TRUE_LITERAL = 51;
		static public final short FALSE_LITERAL = 52;
		static public final short CHARACTER_LITERAL = 53;
		static public final short STRING_LITERAL = 54;
		static public final short NULL_LITERAL = 55;
		static public final short PROC = 56;
		static public final short OPERATOR = 57;
		static public final short GT = 58;
		static public final short MULT = 59;
		static public final short FOREACH = 60;
		static public final short FOR = 61;
		static public final short ENDCHOOSE = 62;
		static public final short ENDFOREACH = 63;
		static public final short ENDIF = 64;
		static public final short ENDLAMBDA = 65;
		static public final short ENDLET = 66;
		static public final short ENDPROC = 67;
		static public final short ENDWHILE = 68;

		static public final String[] NAMES = {
			"EOF",
			"NETWORK",
			"IDENTIFIER",
			"LPAREN",
			"RPAREN",
			"PORTCONN",
			"COLON",
			"IF",
			"THEN",
			"ELSE",
			"END",
			"IMPORT",
			"EQ",
			"SEMICOLON",
			"MAP",
			"LBRACE",
			"RBRACE",
			"BEGIN",
			"VAR",
			"DO",
			"CHOOSE",
			"IN",
			"COMMA",
			"LBRACK",
			"RBRACK",
			"DOT",
			"ALL",
			"EDGE",
			"DOUBLECOLON",
			"MUTABLE",
			"EQCOLON",
			"FUNCTION",
			"PROCEDURE",
			"MULTI",
			"OLD",
			"LET",
			"CONST",
			"LAMBDA",
			"COLONEQ",
			"WHILE",
			"ENTITIES",
			"STRUCTURE",
			"ENTITY",
			"ENDNETWORK",
			"LT",
			"ARROW",
			"BAR",
			"INTEGER_LITERAL",
			"LONG_LITERAL",
			"FLOATING_POINT_LITERAL",
			"DOUBLE_LITERAL",
			"TRUE_LITERAL",
			"FALSE_LITERAL",
			"CHARACTER_LITERAL",
			"STRING_LITERAL",
			"NULL_LITERAL",
			"PROC",
			"OPERATOR",
			"GT",
			"MULT",
			"FOREACH",
			"FOR",
			"ENDCHOOSE",
			"ENDFOREACH",
			"ENDIF",
			"ENDLAMBDA",
			"ENDLET",
			"ENDPROC",
			"ENDWHILE"
		};
	}

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pjctUO5CNMXqzDsi0iqGs2AAYm0hghe2WcL5XKOCaWEUUe194WEIiv1ua2IX0K4#Q04GC" +
		"gfcl07F2gzvh3bND$TRgcfwTxPcV4#$tXystlSxhIgNhhLAxTNgAoQwaXRMHMDwevT9W2$3" +
		"ChjOeAQ3drfwRKYmxII#IZtwcGob5dzInTJFNfFDf0bz8LL9SkKi$GPJIAvj6Dr9UEg8ib$" +
		"HAJ$YWzHe$J4$Ga7Q2dw6bwXkRJMNGsdKCTgPFcQlVO7tHOZQLcj4BLfWA8vawWWwewRzLS" +
		"DGRSazrSyjlSyfghpbJdgZDf2kscHScvggOwHTM4lVdKXHLLWBsd2pS8U$z1xmct0NL6l9j" +
		"RQ7C$f2DKMvUe7b6r#0yUauAzk$5J2znw9hw0tXVkFjXxeUeexLmCRYprMcgkhh6vpuBhJ3" +
		"yZ1Nk7qWww3TmykeyEeQSBQ8pcegSFKXeV4kuzu8wWIYvspGXNjKSxzwSJA9joA9TEfCefs" +
		"Di3BLm7$Nkbj9FcPjZSfORRrMFlcUeKMcdREntsZgTJg3gTYZ7sJ$es1MuDQgMMmjuo4dCo" +
		"kFd2dOvsdaRRf7#lyd0Rqs3rcitz5xYxUHeDKhLe6tftRchzgmw2MmlvwYdDlJlIlvIbdXD" +
		"xjtcuJP1lkyqz3UsSfwhmhOYzYyPmxnIuTT2$Tu3RYbhGWyBzLhWFWzj61OJxdeTx5GXbFT" +
		"mVUJhThIK5xdQqqdPm4UPH3kxxuBQYdjBEsHvkMxJhJsukLTDCjK$TaI9tjyLLkpLNIJkhU" +
		"uKxHBZbFTn#o9Flvggxq6UJKhDNrYJOgqvJDTJfmkqjzYx1k2fMFQITyptSaI0qzzXxhjYR" +
		"JJ#bPE$vF8eQgRQqcVBnBb33nDvXy6LZNiq0jm3hv2gCha9LbngeqVmEVADfYysDhTD4j4L" +
		"YhcPQlaPqkRrMMNFeKfe9dwvPeQhliNKEjLRzREOOpqgMtDO$L00MDL9TLJfyg#mzuG7LbY" +
		"VJDjKPt64UxYrIlyXQDLfT1FiAgPqwGmt2xFqmjRq8UHhHf#eop1YqB0qKxgz6xzUuVRi9S" +
		"IqJjF4ZI4i#fcvGvz1dr8YFq6#ga#vR#itgMnMIyJs12laV7kxhwDl$9E1#e7Oavt8VTO6g" +
		"WNRkJk#fxJAc2ioOQgN68RO3kFTxkCSmikwBprKPFAdaCOKTxdsw7ynRr3frgze2Mxj96tT" +
		"NIzGizQJCdzvkfZfRpLTp4p3FmpmlcVceUaezZ7xjesU$Ue4AUAum1u3vc7fCc4CzpFF1l3" +
		"a1yt8UdOHvIBsiyi4SZX6GZ$t3p1sQJ9DeAjqapDaUvjMeuUG4p9wOsINFrvjf8Iq0Sp5Mc" +
		"sne5z0oOURBpwt2tEfX3W5pPmBcSFuW2VDssgK6WBc7zjATwZum7n3clRIV7WBr#NXpHYq2" +
		"yyK4pDNydoJCLz6Y3u7vjjf8xwf7C6ux2RCAVQ9UeY$q2aWVUPXFWFcblJuqKvDv7cA#Kll" +
		"e6$gEboHX$g0goDhm2quc#Kg16JJxpNWQIpVGEAn9#doSgz9WxmmQ3OqmpfWLrGcsdOMsxX" +
		"XregfCroTXJbOdgQfWBjHd6TbhgecTeg7gu2nJg5R2pfcgK4rHzTHKVTP2BNQhXj6zHcsKl" +
		"IOVAqjZf5T9CcvRugS5vcShr1rj16PhiRDTr4xPPt9L6zK1ThuihLz8hBf5xLHTC9FpLH$L" +
		"LmrI0zNW97Rg6N8jcDT5zXarqc7dA7MznOITuwb8FIrxS04e4zKCkp$d83nJpLPtguLg7eN" +
		"KJKdiV11w2y5SO3EjSPjkmlaeRndiN86wRP3stwGsgxrggzfcCwUh7MgbkWtCdMgvkXtjNp" +
		"9pXzgbxWJp7hJj$TAV5ZFJCORswxO5yu1wNENmCPwZzg8$NtBqvujoPdbUlQ9U9VsKtBRMq" +
		"uW8urO$1H3D97T$8kPAQ9qg6eKg4#$ek7K$AJBjSmD5#nF#gqr$HXzXYY#6oGF$PqoAprHN" +
		"$0Kxhqk1IJ5CYxlUmOne$MaxiMv9QLYvhFuiC5eHvXkct0AiM#HkMwnR#bcN4ZDo3YIvKv7" +
		"RJdiTmgFMGgPYPFVoClzKsqRxCmbJZL3hBQPTybzcobt0nLIFKxmnj3tUk5MBZyFE9EDMhR" +
		"6PSUVASRNjdvehfSo$CTEx3b4Cq$kaoenQOQr3aQUKMSeiPPOoIvb$HsRqxlmSrIMSwgWL$" +
		"KYVqslqDQqk8NKLKlzTGleB9UP#nPFwfYFrhHBplbDYwiSbfXujCVNx4bD$BYbLLIeXTOtd" +
		"Rqlwj7k9tJljNUdJFFfvq6yIKLVwLb33lkdfPvRQGsJ$xOJYy9n$pRdGv0exXuXgIXLZ1uq" +
		"wo$tN6h7ecZYbQsq$NbNXngFhzB9qahXbufMgYWpqWZYfEfSlJho#nsOvxWEHntkkSZ$hac" +
		"henveXFlBZfpFSDBe9iPbmmtYNfNBebmfeDIMjcuNMpQKYQe9wNOMxRrDgHitfLlJ7QNGwr" +
		"P3V3BQBII#KykjIFJeNbjMdys5z0$JEHR3r4k5gTpTugt47RKJ5u1OBDopSIiBT3ghFm$NP" +
		"t4pX3g6QaE7G7Pu2Tneuqy0j0ZUJwe3NNhX#S3CGexcPA2liuMRRt3x2jKhqKG0$oRcvyfE" +
		"6KMh5Xx6cQMunk5TGR#66uhHoURhMvau1DpOzEVTwcaIJmUsDyLK9CM7C5SrD0pTWxDq5xb" +
		"Iii6vsXBiAt3KqdMRGJ9f5isbE2jmGIii19S$4X2beSnSRRbuSUuknKqIu$S5jJnqmBplAN" +
		"rqpK#26gGMr12KaCQEb7pMt4xXTeA6v9yVXXh2xHBYNWfkBsfKt$Ti$nVvT3sukLK4VQtlz" +
		"Tlyke9t2zSNXwdmHRbLmJw5gw2TDpqbfNEMO$jLMXuIRQSyZlIv6nhENkz339IbHIohsNYh" +
		"ZMOUTtCl0rNNHt8fnkUJXPXbknJ$9hIrSQzsexk36R#SY3tSmOiUaQ6z5wHKzUhkRUHGIRZ" +
		"$4h4H8SulYShTvk3wxn5JirNCfJSPXaN3Jp3mAemGVMZqRlbpHoCRO2yZOoSRx99lhhLDYh" +
		"cPQFbrYPAqgCcFvSlXqpUAlLTredCtCyQGcjrMFLxqNhHDVcjstrYpqqMs8Jul33JlwLgza" +
		"kP9$YCcNsbwaMp1Jycr2ULk4csdqCXFqRH5MY4HjN9JI6jcV6eERXVDnEUdRXgPlYqKd9y4" +
		"QcOkMJiJrfS0Dq3ACuZGPFPM5syzmzGpo2RTyN6vYUqjgPytiZPL1zwbUnSEmE4mZpJbZ87" +
		"QuOfa$8#CmzM$uZyTMpPo0d$6o1#NARXI6JpFBWJaNFoSaiBCaPZ8xRwSTOgSU$zPyBJBdY" +
		"w78MoFXFg$d#V7QEHGo3qmzzoiASuamY#J7Qjj0N6RESTkPXtArdLNWvWdJ9ym0JYd5A2qh" +
		"uNgOUTpCJ7Ec641b89fPJfWLQIb2VMG5h1INMSbcda6rP3pqXNPVn0UJCFjYfkYrOOHObMF" +
		"RMTq#cLZxJLVCoIBKiAUSi8fHyWYRcMthwlLjA7HBPkgzKFUdtyp723EYqGabTW7pSeoa7c" +
		"3rafhvOjQ5gcWZlTSK8PyUYoNjhTRkwyDUQAsvket2k1TOupPgPrZip99pOqzfVRrUZdFOM" +
		"LvQgLXszEkXKJ9JZyxEiYP4zfdE3Zi7o3uM5ZlpA1qpMU#OOTBVObMncRhFEu5NB3V0cvFE" +
		"bLlCENoWpHmip64cN6J6KARqfcx$jJI89Y9lbitiX50Nn1Q3s0FnlPAsxI0PjpxaA9R#Z33" +
		"TOyXQCNhA69WejvzeVzue$Pc7#s4nuocPoV9G6iJI3aF0nDlLduZ9WFGK3VGdtdP$ikj9cM" +
		"dQrc9Q8VZDMSLHdZ355yEalFyLKsoAm$mhTj9PoPcGN5UPsFMYp8ZMSTZfCwM5J7#6ZPPXO" +
		"gPa6mrJ0wUTL5rYQgPafpa7GW$p83g6xFuqwv2Kr0FIoxBHsv$7PMSI9kmqJBlalywKK2pJ" +
		"Z1VN6D9dJ2$p$sBSKdg46N#k79UTVsgkb3B$laplEcHoETQXusCwh91ro8ufPPOoIvcbp5B" +
		"ctv7fkZkpdCEe5RMcDjGsIMgVlvJx$rDgt1IxTzfvVeFX3lUErOTqPtFJavX#D8hjcnvyNf" +
		"xphpdjJAxvCMDaD2rtZPf52Ipon8fsAyYAUDP4qcbhV6kThK6R4#RsvigG#32x7k#vogDHC" +
		"vc6Q5apXDJXATPVKSj3EaaAeJs9Da3#GnIy4JfrYTBUXZiGuJQ8xm198$AbGoxI#QqoWfz4" +
		"$8a4PUmqxkUMwpi$DXqsa#gEiYeJfS#3smvnc#0kG3pYWiyY$a22ifUYl0UYOTyX8lylS3y" +
		"pwIyWxp6Ya2ysdxzir1#w6D82SZtaTyXUc5fWqexYzOIfPn$aMsmuWr7sEz0x7N4T8MWN$q" +
		"#Gnh6SDDYbph3yWTgcJf#XoNyoSLsDtYh8UGWFW$igTAOOpgc86sbqePCUDleZu6z2b164p" +
		"cdWvi7juMqVkXHwy6PSWFpxJDn6#E#6$akGjsBr0$T2$m6q#GOJNWOvOFmVcVelXFyJo5l8" +
		"FrT7k9Xt6VSRKzStKUOFS7T6TJ8AaFSrO#EdAEixK$Oko5ZmGuRv5MnhRz8M8JxD#d8w68v" +
		"b#Z56WpLD7hHPi8R9yn7IHXWcnd96GtSR9HAKKLsxw2kCd#0vfgxwsn7Kbp1MWYqSzco6VH" +
		"#3LvkeR0z4J3Ry$f2ZiULcl8jnXRuBNeCqvFDFYattpK1QRwIz3sbXsl92#3zqrMyuT34$V" +
		"5LDljqGp5F$h5Yz0CQWlnvHPWwuOOGnjuEOxu6XZh9M6rVN1sCb4tCoX3uBR4FS2hWVkEg8" +
		"VWYYBNnBe3$Fv7q5iiNuxuSyP$m78I#QV1dmctuFxOTD#rrrrQmzHhSHTDzsC4z667Ck4sj" +
		"4g9BHVzLoCm#WNKV2HL$HD6UPfWw7Z8k#yuycAWCRqp0U$8WEeftz3yNgbq5P6UDCFGF63P" +
		"eomF1XJ8VAclXoo8##264EXYf4o$3hTUT4KyyCOyDgb8qndcxwBF0bTAevwfc9y9ccNAmjP" +
		"Jv3FNPPuN0rvCEOyRT56jPn$rEGdqsvXn5tWU5Y$lhHBw5B3CCzFtqcpn73kGBI4tdkWzlH" +
		"nEd#Rmb16uNwchX#fXwTKO$5qV92u$3w6UwCQ5mOwqOw#jr$5VXcxYYCmT0imwwFj2#GThO" +
		"f0$eXCuv265UX5SO$1tANi$ucVYFAA39bJKNuNjD#M0jz3o9ymD6cZI7TB7$wR4STiVvbx8" +
		"CkzfVGeuwoduT#NxXFG613e1VSbqtQ7aUv$PrrmZgnrBWJJFfx9eyP0w6sbfir0MrH4tAjr" +
		"ovQvexpwcIjDRf$n4yditVHasWBp7LQRi9D8$aGtoSPny7R6nlsBOMD7oNMLmsiVLYDWViw" +
		"t3lHrzLCsxpgq5lbAFEWYViQkgt1lC6m3xjiAulq5rqyFN$VSDMnLdJS#OuwuYkxofjfkG7" +
		"ivxv#S8UWtqmx1Nl6jy#t1tgOxu5cngPVJ5qnLkbe77siMQeW6WuOswoz7$b$CthwkyETYE" +
		"yIcpzipcjPGqm#wFXpuUwAwkWr8R3Rf6zpsJWcDXnPCvMPpu6OjZDvEhhoEFRkW5at$9WNW" +
		"I$YjL590di#YVg3ZvYuxsDr$0kjlJ$B1vqJuF$Hj445#7zswTw2LmEJNYrYduCHC6c5#enf" +
		"U5WxWoTvwvQ5yrBGp9yWpcDPnN3pNRmfnjNx6jezoxH7sRBUyY9ZoO#pT13dnwnlZMvbjwx" +
		"XTuNUPPO$DDHLLak7lx4tRsYREywm0mdYDrfk06T8VnTJhbbt0vNWtmYt8T86nSjlz6ys#h" +
		"gTSFx8McJiu5Yz0FQ8u5xBxyioUPSwohadLfyc6hTFDCwtrw6$mr7sR8JDUJzu94uTzpjqi" +
		"Tu7VpV#n#7NzvqlZDwt4J$cvEsnPVWVZFhTTudWTCjLLHqwPP3di2F$EuuwP1kT71F6cXSg" +
		"YYqpr2Ws7D3tagOuipmJZKjNKNyGTvvG7RVjfgpwhd3p#7g#d3XvXyNNzPirp$#ZemxvaJE" +
		"0lWl5wgjCLxcTZLqE6q8B7Vg7AUx3lzg#VNmN$yA$yG$yFN$7$#P$yHFyE7$DN$4$#Hka7#" +
		"Kl6ISCtWZ1pPRDryxSdo$a1dm1dy$r6JS$leGRykMIWlMC1q0kutQCUSrjk7KCknLZX#2Mu" +
		"czXugf2ga1okH9Nb7JC16ukQSqWvly3#6h8bU9hmZWJyM3n3pAfstaBR#PDZ9MCrq4QsypX" +
		"dC7fnZzCtlg$8wyGtoY#5k$hECW1LZo2wTWnetaENoDk1tctv#dYJc6Sb7Y6NVP4di0pnIV" +
		"$cS3Zv7q3P2ptv1xSdRjnL#x2dRaJT#Jnt9hF5WtxAsukECRYAdcVfLq#ayjmfadNuJhiPv" +
		"yTgYtlMboEovgOCuoRprbildld6X2SvFWKhext2IRsT0ZkTdmoL#DipZRvS9BYRNoRQAoIz" +
		"qfUW$TgyLVWyZnIV7KPwpcVo$NisW#5u1x7QoLKn6aSuY7SbqyqwIT1SB$Y7CvZx0kydh$b" +
		"J$bZ$eG$CneV6VS8lyVlYmztKzvlOk#HzztyWBXloFirVfCS3xyhxxTD23TgFioly#TyY5$" +
		"Yb$aLM#z5VeQnP#5zW9$cPoNkINxEfBx0yf$eZ5CN7nJVy$omk8$9#r5vFy8xyBwT7#87#N" +
		"TU3Fz2ndsBbqDm$kQbl4Zqzl8Utirtm8UJ1lox#CwOEi$Y#NmJtmpV0fuj$m6Wlxw$YHGX3" +
		"g9ekOYFvYCy7txivX15kocBHi5romeH7ss5tbRuPy0$MaI9h1Jn4MwZ44KpvMkV0Ed#NeKm" +
		"vW54KMSAoXSvsn7UBc6$nAs1Vmtyg#6kbg$A$TGB$bueHz$MUy0$IxwA2K82nasZiOWVYtZ" +
		"C2OYIBsSw8MqWyaz7MCjiwC#c4Cr1l1v9Qn6dPPs8$kgJ88fw8yyuw6fPWB2MMqJqbtu4KJ" +
		"GU#kCHdYlVt2Y8dth2rL$KT9Tln4Y#4#kAk8XqGBW3ohH4X$qYxU5lZxHhuEy86OpmO8Gjy" +
		"PDUJOOXRgA8$lBFHnWV44Ktme##XoYw5MdhuQw7Emdk9BZ5S2SZVJBSOd1neuLO$cAqWtOt" +
		"8Bm1kbECB4APE3L3566TX2YQXtRJ$wczMBuh2qBI8Ecq2McRa6SgP2JIsY7S3dxz$$xNmRy" +
		"PxcQuJS6v2cuokLh43mbI4$WjyHat3UA718qRCFuGRG5dY#W496p5#uoUZwv4sfLmcy5j1f" +
		"rcY6yEVtFvEanvP8Y8ZwR1dGQTriZJ6k7MuWz1Wf0qbp$3w0Mf5TnMueOWQGut7P91BP7U4" +
		"kdwMthzNmHHDnsIGTt0xIRVvIcHZKRw6XbXP82H$aQM6LbYPAaH$PlXDd3RYlZeZly2jb6$" +
		"u0==");

/*******************************************************
 *  Inject code for custom error handling in the parser class.
 *******************************************************/
  // all errors encountered during parsing is stored in the array parseProblems. This includes lexical, syntactical and semantic error (multiple initialization actors et.c.)
  public java.util.TreeSet<String> parseProblems = new TreeSet<String>();
  public void newError(String msg, Symbol token){
      parseProblems.add(msg + " At row " + Symbol.getLine(token.getStart()) + ", column " + Symbol.getColumn(token.getStart()));
  };
  public void printParseProblems(){ printParseProblems(System.err); }
  public void printParseProblems(PrintStream out){
    out.println("number of problems: " + parseProblems.size());
    for(String msg : parseProblems){
      out.println("ERROR: " + msg);
    }
  }

  // parser plug-in methods that are called when the parser encounters a syntactical problem
  class Events extends Parser.Events {
    public void scannerError(Scanner.Exception e) {
      parseProblems.add(e.getMessage());
    }
    public void syntaxError(Symbol token) {
      // This method is always called when a problem is encountered, even if it is repaired.
      // beaver.Parser$Exception is thrown if recovery fails.
      String value = token.value != null ? token.value.toString() : Terminals.NAMES[token.getId()];
      parseProblems.add("unexpected token \"" + value + "\" at " + Symbol.getLine(token.getStart()) + ", " + Symbol.getColumn(token.getStart()));
    }
    public void unexpectedTokenRemoved(Symbol token) {
      String value = token.value != null ? token.value.toString() : Terminals.NAMES[token.getId()];
      parseProblems.add("parser recovered after removing token \"" + value + "\" at " + Symbol.getLine(token.getStart()) + ", " + Symbol.getColumn(token.getStart()));
    }
    public void missingTokenInserted(Symbol token) {
      String value = token.value != null ? token.value.toString() : Terminals.NAMES[token.getId()];
      parseProblems.add("parser recovered after inserting token \"" + value + "\" at " + Symbol.getLine(token.getStart()) + ", " + Symbol.getColumn(token.getStart()));
    }
    public void misspelledTokenReplaced(Symbol token) {
      String value = token.value != null ? token.value.toString() : Terminals.NAMES[token.getId()];
      parseProblems.add("parser recovered after replacing token \"" + value + "\" at " + Symbol.getLine(token.getStart()) + ", " + Symbol.getColumn(token.getStart()));
    }
    public void errorPhraseRemoved(Symbol token) {
      String value = token.value != null ? token.value.toString() : Terminals.NAMES[token.getId()];
      parseProblems.add("parser recovered after removing token \"" + value + "\" at " + Symbol.getLine(token.getStart()) + ", " + Symbol.getColumn(token.getStart()));
    }
  }

  {
    // initialization, before the constructor
    report = new Events(); // Use error handler in parser
  }

/*******************************************************
 *  Help routine that parses a file, given its name.
 *  A compilation unit is always returned, containing all parseProblems encountered during parsing.
 *  If a Parser.exception is thrown a CompilationUnit with an empty AST is returned.
 *******************************************************/

  public NetworkDefinition parse(String fileName){
    return parse(new java.io.File(fileName));
  }
  public NetworkDefinition parse(String path, String fileName){
    return parse(new java.io.File(path + "/" + fileName));
  }
  public NetworkDefinition parse(java.io.File file){
     NetworkDefinition network;
     parseProblems = new TreeSet<String>();
     java.io.FileReader fr = null;
     try {
       try {
         fr = new java.io.FileReader(file);
	       NlScanner scanner = new NlScanner(new java.io.BufferedReader(fr));
         network = (NetworkDefinition)parse(scanner);
         fr.close();
       } catch(CalParser.Exception e) {
         // build empty compilation unit for failed error recovery
         // The problem is added to parseProblems[] by the syntaxError() method added to the parser above.
         network = new NetworkDefinition(file.getName());
       } finally {
         if(fr != null){ fr.close(); }
       }
     } catch (java.io.FileNotFoundException e){
       parseProblems.add("file not found: " + e.getMessage());
       network = new NetworkDefinition(file.getName());
     } catch (java.io.IOException e){
       parseProblems.add("error reading file: " + e.getMessage());
       network = new NetworkDefinition(file.getName());
     }
//     network.setSourceFile(file);
//     network.parseProblems = parseProblems;
//     for(Problem p : parseProblems) {
//       p.setSourceFile(file);
//     }
     return network;
   }

  private enum NetworkBodyPartKind{ IMPORT, VAR_DECL, ENTITIES, STRUCTURE, TOOL_ATTRIBUTE; }

/******************************************************************************
 * Needed by CommonParser.beaver
 * Repeated in both NlParser.beaver and CalParser.beaver
 *****************************************************************************/
   private GeneratorFilter makeGeneratorFilter(TypeExpr type, ArrayList varList, Expression e, ArrayList filterList){
    DeclVar[] vars = new DeclVar[varList.size()];
    for(int i = 0; i<varList.size(); i++){
      Symbol symbol = (Symbol)varList.get(i);
      vars[i] = new DeclVar(type, (String)symbol.value, null);
    }
    Expression[] filters = filterList == null ? new Expression[0] : (Expression[])filterList.toArray(new Expression[filterList.size()]);
    return new GeneratorFilter(vars, e, filters);
  }
  class ParenthesSymbol extends Symbol{ // used by the parser to wrap subexpressions that are enclosed by parentheses, i.e. do not add them to a ExprBinaryOp sequence.
     ParenthesSymbol(Symbol s){
       super(s.getId(), s.getStart(), s.getEnd(), s.value);
     }
  }

	public NlParser() {
		super(PARSING_TABLES);
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		switch(rule_num) {
			case 4: // lst$network_body_part = network_body_part
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
			}
			case 5: // lst$network_body_part = lst$network_body_part network_body_part
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
			}
			case 10: // network = NETWORK IDENTIFIER.name opt$type_parameter_block.typePars LPAREN opt$actor_parameter_list.valuePars RPAREN port_decl_list_opt.inputPorts PORTCONN port_decl_list_opt.outputPorts COLON opt$lst$network_body_part.body end_network.end_network opt$SEMICOLON
			{
					final Symbol name = _symbols[offset + 2];
					final Symbol _symbol_typePars = _symbols[offset + 3];
					final ArrayList typePars = (ArrayList) _symbol_typePars.value;
					final Symbol _symbol_valuePars = _symbols[offset + 5];
					final ArrayList valuePars = (ArrayList) _symbol_valuePars.value;
					final Symbol _symbol_inputPorts = _symbols[offset + 7];
					final CompositePortDecl inputPorts = (CompositePortDecl) _symbol_inputPorts.value;
					final Symbol _symbol_outputPorts = _symbols[offset + 9];
					final CompositePortDecl outputPorts = (CompositePortDecl) _symbol_outputPorts.value;
					final Symbol _symbol_body = _symbols[offset + 11];
					final ArrayList _list_body = (ArrayList) _symbol_body.value;
					final Map.Entry[] body = _list_body == null ? new Map.Entry[0] : (Map.Entry[]) _list_body.toArray(new Map.Entry[_list_body.size()]);
					final Symbol _symbol_end_network = _symbols[offset + 12];
					final String end_network = (String) _symbol_end_network.value;
					
        NamespaceDecl ns = null;
        ArrayList varDecls = new ArrayList();
        ArrayList structure = new ArrayList();
        ArrayList<java.util.Map.Entry<String,EntityExpr>> entities = new ArrayList();
        ArrayList<ToolAttribute> toolAttributes = new ArrayList();
        for(Map.Entry part : body){
            ArrayList all = (ArrayList)part.getValue();
            if(all != null){  // entities and structure may be empty. Then the parser return null.
                switch((NetworkBodyPartKind)part.getKey()){
                case IMPORT:
                     System.out.println("UNSUPPORTED, import is ignored.");
                     //TODO
                     break;
                case VAR_DECL:
                    varDecls.addAll(all);
                    break;
                case ENTITIES:
                    entities.addAll(all);
                    break;
                case STRUCTURE:
                    structure.addAll(all);
                    break;
                case TOOL_ATTRIBUTE:
                    toolAttributes.addAll(all);
                    break;
                }
            }
        }
        
        return new Symbol(new NetworkDefinition((String)name.value, 
                          ns, 
                          typePars == null ? new ParDeclType[0] : (ParDeclType[])typePars.toArray(new ParDeclType[typePars.size()]),     // typePars,
                          valuePars == null ? new ParDeclValue[0] : (ParDeclValue[])valuePars.toArray(new ParDeclValue[valuePars.size()]), // valuePars,
                          new DeclType[0],      // typeDecls, NOTE, can not be expressed in NL
                          (DeclVar[])varDecls.toArray(new DeclVar[varDecls.size()]),             // varDecls
                          inputPorts, outputPorts,
                          (Map.Entry<String,EntityExpr>[])entities.toArray(new Map.Entry[entities.size()]), // entities
                          (StructureStatement[])structure.toArray(new StructureStatement[structure.size()]), // structure
                          (ToolAttribute[])toolAttributes.toArray(new ToolAttribute[toolAttributes.size()])
                          ));
			}
			case 11: // network_body_part = import_part.part
			{
					final Symbol _symbol_part = _symbols[offset + 1];
					final ArrayList part = (ArrayList) _symbol_part.value;
					 return new Symbol(new AbstractMap.SimpleEntry(NetworkBodyPartKind.IMPORT, part));
			}
			case 12: // network_body_part = network_decl_block.part
			{
					final Symbol _symbol_part = _symbols[offset + 1];
					final ArrayList part = (ArrayList) _symbol_part.value;
					 return new Symbol(new AbstractMap.SimpleEntry(NetworkBodyPartKind.VAR_DECL, part));
			}
			case 13: // network_body_part = entities.part
			{
					final Symbol _symbol_part = _symbols[offset + 1];
					final ArrayList part = (ArrayList) _symbol_part.value;
					 return new Symbol(new AbstractMap.SimpleEntry(NetworkBodyPartKind.ENTITIES, part));
			}
			case 14: // network_body_part = structure.part
			{
					final Symbol _symbol_part = _symbols[offset + 1];
					final ArrayList part = (ArrayList) _symbol_part.value;
					 return new Symbol(new AbstractMap.SimpleEntry(NetworkBodyPartKind.STRUCTURE, part));
			}
			case 15: // network_body_part = tool_attribute_block.part
			{
					final Symbol _symbol_part = _symbols[offset + 1];
					final ArrayList part = (ArrayList) _symbol_part.value;
					 return new Symbol(new AbstractMap.SimpleEntry(NetworkBodyPartKind.TOOL_ATTRIBUTE, part));
			}
			case 16: // lst$network_decl = network_decl
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
			}
			case 17: // lst$network_decl = lst$network_decl network_decl
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
			}
			case 20: // network_decl_block = VAR opt$lst$network_decl.d
			{
					final Symbol _symbol_d = _symbols[offset + 2];
					final ArrayList _list_d = (ArrayList) _symbol_d.value;
					final DeclVar[] d = _list_d == null ? new DeclVar[0] : (DeclVar[]) _list_d.toArray(new DeclVar[_list_d.size()]);
					 return _symbol_d;
			}
			case 21: // network_decl = var_decl.d SEMICOLON
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 return _symbol_d;
			}
			case 22: // network_decl = fun_decl.d
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 return _symbol_d;
			}
			case 23: // network_decl = proc_decl.d
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 return _symbol_d;
			}
			case 24: // lst$entity = entity
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
			}
			case 25: // lst$entity = lst$entity entity
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
			}
			case 28: // entities = ENTITIES opt$lst$entity.l
			{
					final Symbol _symbol_l = _symbols[offset + 2];
					final ArrayList _list_l = (ArrayList) _symbol_l.value;
					final java.util.Map.Entry[] l = _list_l == null ? new java.util.Map.Entry[0] : (java.util.Map.Entry[]) _list_l.toArray(new java.util.Map.Entry[_list_l.size()]);
					 return _symbol_l;
			}
			case 29: // entity = IDENTIFIER.ID EQ entity_expr.e SEMICOLON
			{
					final Symbol ID = _symbols[offset + 1];
					final Symbol _symbol_e = _symbols[offset + 3];
					final EntityExpr e = (EntityExpr) _symbol_e.value;
					 return new Symbol(new java.util.AbstractMap.SimpleEntry((String)ID.value, e));
			}
			case 34: // entity_expr = IDENTIFIER.id LPAREN opt$param_assign_list.l RPAREN opt$tool_attribute_block.a
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_l = _symbols[offset + 3];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_a = _symbols[offset + 5];
					final ArrayList a = (ArrayList) _symbol_a.value;
					 return new Symbol(new EntityInstanceExpr((String)id.value, l == null ? new Map.Entry[0] : (Map.Entry[])l.toArray(new Map.Entry[l.size()]),
                                                                                                                          (ToolAttribute[]) (a==null ? new ToolAttribute[0] : a.toArray(new ToolAttribute[a.size()]))
                                                                                                                         ));
			}
			case 35: // entity_expr = IF expression.e THEN entity_expr.t ELSE entity_expr.f end_if
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_t = _symbols[offset + 4];
					final EntityExpr t = (EntityExpr) _symbol_t.value;
					final Symbol _symbol_f = _symbols[offset + 6];
					final EntityExpr f = (EntityExpr) _symbol_f.value;
					 return new Symbol(new EntityIfExpr(e, t, f));
			}
			case 38: // entity_expr = LBRACK opt$entity_expr_list.e RBRACK
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					 return new Symbol(new EntityListExpr((EntityExpr[])(e==null? new EntityExpr[0] : e.toArray(new EntityExpr[e.size()])), null));
			}
			case 39: // entity_expr = LBRACK entity_expr_list.e COLON for_generator_list.g RBRACK
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					final Symbol _symbol_g = _symbols[offset + 4];
					final ArrayList g = (ArrayList) _symbol_g.value;
					 return new Symbol(new EntityListExpr((EntityExpr[])(e==null? new EntityExpr[0] : e.toArray(new EntityExpr[e.size()])), (GeneratorFilter[])g.toArray(new GeneratorFilter[g.size()])));
			}
			case 40: // param_assign_list = param_assign.p
			{
					final Symbol _symbol_p = _symbols[offset + 1];
					final Map.Entry p = (Map.Entry) _symbol_p.value;
					 ArrayList l = new ArrayList(); l.add(p); return new Symbol(l);
			}
			case 41: // param_assign_list = param_assign_list.l COMMA param_assign.p
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_p = _symbols[offset + 3];
					final Map.Entry p = (Map.Entry) _symbol_p.value;
					 l.add(p); return _symbol_l;
			}
			case 42: // entity_expr_list = entity_expr.e
			{
					final Symbol _symbol_e = _symbols[offset + 1];
					final EntityExpr e = (EntityExpr) _symbol_e.value;
					 ArrayList l = new ArrayList(); l.add(e); return new Symbol(l);
			}
			case 43: // entity_expr_list = entity_expr_list.l COMMA entity_expr.e
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final EntityExpr e = (EntityExpr) _symbol_e.value;
					 l.add(e); return _symbol_l;
			}
			case 44: // param_assign = IDENTIFIER.ID EQ expression.expression
			{
					final Symbol ID = _symbols[offset + 1];
					final Symbol _symbol_expression = _symbols[offset + 3];
					final Expression expression = (Expression) _symbol_expression.value;
					 return new Symbol(new java.util.AbstractMap.SimpleEntry((String)ID.value, expression));
			}
			case 45: // lst$entity_statement = entity_statement
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
			}
			case 46: // lst$entity_statement = lst$entity_statement entity_statement
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
			}
			case 49: // structure = STRUCTURE opt$lst$entity_statement.l
			{
					final Symbol _symbol_l = _symbols[offset + 2];
					final ArrayList _list_l = (ArrayList) _symbol_l.value;
					final StructureStatement[] l = _list_l == null ? new StructureStatement[0] : (StructureStatement[]) _list_l.toArray(new StructureStatement[_list_l.size()]);
					 return _symbol_l;
			}
			case 50: // entity_statement = entity_port.src EDGE entity_port.dst opt$tool_attribute_block.a SEMICOLON
			{
					final Symbol _symbol_src = _symbols[offset + 1];
					final PortReference src = (PortReference) _symbol_src.value;
					final Symbol _symbol_dst = _symbols[offset + 3];
					final PortReference dst = (PortReference) _symbol_dst.value;
					final Symbol _symbol_a = _symbols[offset + 4];
					final ArrayList a = (ArrayList) _symbol_a.value;
					 return new Symbol(new StructureConnectionStmt(src, dst, (ToolAttribute[])(a==null ? null : a.toArray(new ToolAttribute[a.size()]))));
			}
			case 51: // entity_statement = for_generator_list.g DO opt$lst$entity_statement.s END
			{
					final Symbol _symbol_g = _symbols[offset + 1];
					final ArrayList g = (ArrayList) _symbol_g.value;
					final Symbol _symbol_s = _symbols[offset + 3];
					final ArrayList _list_s = (ArrayList) _symbol_s.value;
					final StructureStatement[] s = _list_s == null ? new StructureStatement[0] : (StructureStatement[]) _list_s.toArray(new StructureStatement[_list_s.size()]);
					 return new Symbol(new StructureForeachStmt((GeneratorFilter[])(g.toArray(new GeneratorFilter[g.size()])), s));
			}
			case 52: // entity_statement = IF expression.e THEN opt$lst$entity_statement.t_stmt END
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_t_stmt = _symbols[offset + 4];
					final ArrayList _list_t_stmt = (ArrayList) _symbol_t_stmt.value;
					final StructureStatement[] t_stmt = _list_t_stmt == null ? new StructureStatement[0] : (StructureStatement[]) _list_t_stmt.toArray(new StructureStatement[_list_t_stmt.size()]);
					 return new Symbol(new StructureIfStmt(e, t_stmt, null));
			}
			case 53: // entity_statement = IF expression.e THEN opt$lst$entity_statement.t_stmt ELSE opt$lst$entity_statement.f_stmt END
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_t_stmt = _symbols[offset + 4];
					final ArrayList _list_t_stmt = (ArrayList) _symbol_t_stmt.value;
					final StructureStatement[] t_stmt = _list_t_stmt == null ? new StructureStatement[0] : (StructureStatement[]) _list_t_stmt.toArray(new StructureStatement[_list_t_stmt.size()]);
					final Symbol _symbol_f_stmt = _symbols[offset + 6];
					final ArrayList _list_f_stmt = (ArrayList) _symbol_f_stmt.value;
					final StructureStatement[] f_stmt = _list_f_stmt == null ? new StructureStatement[0] : (StructureStatement[]) _list_f_stmt.toArray(new StructureStatement[_list_f_stmt.size()]);
					 return new Symbol(new StructureIfStmt(e, t_stmt, f_stmt));
			}
			case 54: // lst$entity_indexing = entity_indexing
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
			}
			case 55: // lst$entity_indexing = lst$entity_indexing entity_indexing
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
			}
			case 58: // entity_port = IDENTIFIER.id_port opt$lst$entity_indexing.index_port
			{
					final Symbol id_port = _symbols[offset + 1];
					final Symbol _symbol_index_port = _symbols[offset + 2];
					final ArrayList _list_index_port = (ArrayList) _symbol_index_port.value;
					final Expression[] index_port = _list_index_port == null ? new Expression[0] : (Expression[]) _list_index_port.toArray(new Expression[_list_index_port.size()]);
					 return new Symbol(new PortReference(null, null, (String)id_port.value));
			}
			case 59: // entity_port = IDENTIFIER.id_entity opt$lst$entity_indexing.index_entity DOT IDENTIFIER.id_port opt$lst$entity_indexing.index_port
			{
					final Symbol id_entity = _symbols[offset + 1];
					final Symbol _symbol_index_entity = _symbols[offset + 2];
					final ArrayList _list_index_entity = (ArrayList) _symbol_index_entity.value;
					final Expression[] index_entity = _list_index_entity == null ? new Expression[0] : (Expression[]) _list_index_entity.toArray(new Expression[_list_index_entity.size()]);
					final Symbol id_port = _symbols[offset + 4];
					final Symbol _symbol_index_port = _symbols[offset + 5];
					final ArrayList _list_index_port = (ArrayList) _symbol_index_port.value;
					final Expression[] index_port = _list_index_port == null ? new Expression[0] : (Expression[]) _list_index_port.toArray(new Expression[_list_index_port.size()]);
					 return new Symbol(new PortReference((String)id_entity.value, index_entity , (String)id_port.value));
			}
			case 60: // entity_indexing = LBRACK.LBRACK expression.e RBRACK.RBRACK
			{
					final Symbol LBRACK = _symbols[offset + 1];
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol RBRACK = _symbols[offset + 3];
					 return _symbol_e;
			}
			case 61: // import_part = import_single.i
			{
					final Symbol _symbol_i = _symbols[offset + 1];
					final ArrayList i = (ArrayList) _symbol_i.value;
					 return _symbol_i;
			}
			case 62: // import_part = import_group.i
			{
					final Symbol _symbol_i = _symbols[offset + 1];
					final ArrayList i = (ArrayList) _symbol_i.value;
					 return _symbol_i;
			}
			case 63: // import_single = IMPORT import_kind.k qual_id.qual_id SEMICOLON
			{
					final Symbol _symbol_k = _symbols[offset + 2];
					final String k = (String) _symbol_k.value;
					final Symbol _symbol_qual_id = _symbols[offset + 3];
					final ArrayList qual_id = (ArrayList) _symbol_qual_id.value;
					 return new Symbol(qual_id);
			}
			case 64: // import_single = IMPORT import_kind.k qual_id.qual_id EQ IDENTIFIER.alias SEMICOLON
			{
					final Symbol _symbol_k = _symbols[offset + 2];
					final String k = (String) _symbol_k.value;
					final Symbol _symbol_qual_id = _symbols[offset + 3];
					final ArrayList qual_id = (ArrayList) _symbol_qual_id.value;
					final Symbol alias = _symbols[offset + 5];
					 return new Symbol(qual_id);
			}
			case 65: // import_group = IMPORT import_kind.k ALL qual_id.qual_id SEMICOLON
			{
					final Symbol _symbol_k = _symbols[offset + 2];
					final String k = (String) _symbol_k.value;
					final Symbol _symbol_qual_id = _symbols[offset + 4];
					final ArrayList qual_id = (ArrayList) _symbol_qual_id.value;
					 return new Symbol(qual_id);
			}
			case 66: // import_kind = 
			{
					 return new Symbol("");
			}
			case 67: // import_kind = ENTITY.kind
			{
					final Symbol kind = _symbols[offset + 1];
					 return kind;
			}
			case 68: // import_kind = VAR.kind
			{
					final Symbol kind = _symbols[offset + 1];
					 return kind;
			}
			case 69: // lst$tool_attribute = tool_attribute
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
			}
			case 70: // lst$tool_attribute = lst$tool_attribute tool_attribute
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
			}
			case 73: // tool_attribute_block = LBRACE opt$lst$tool_attribute.a RBRACE
			{
					final Symbol _symbol_a = _symbols[offset + 2];
					final ArrayList _list_a = (ArrayList) _symbol_a.value;
					final ToolAttribute[] a = _list_a == null ? new ToolAttribute[0] : (ToolAttribute[]) _list_a.toArray(new ToolAttribute[_list_a.size()]);
					 return _symbol_a;
			}
			case 74: // tool_attribute = IDENTIFIER.ID EQ expression.expression SEMICOLON
			{
					final Symbol ID = _symbols[offset + 1];
					final Symbol _symbol_expression = _symbols[offset + 3];
					final Expression expression = (Expression) _symbol_expression.value;
					 return new Symbol(new ToolValueAttribute((String)ID.value, expression));
			}
			case 75: // tool_attribute = IDENTIFIER.ID COLON type.type SEMICOLON
			{
					final Symbol ID = _symbols[offset + 1];
					final Symbol _symbol_type = _symbols[offset + 3];
					final TypeExpr type = (TypeExpr) _symbol_type.value;
					 return new Symbol(new ToolTypeAttribute((String)ID.value, type));
			}
			case 78: // actor_parameter_list = actor_parameter.p
			{
					final Symbol _symbol_p = _symbols[offset + 1];
					final ParDeclValue p = (ParDeclValue) _symbol_p.value;
					 ArrayList result = new ArrayList(); result.add(p); return new Symbol(result);
			}
			case 79: // actor_parameter_list = actor_parameter_list.l COMMA actor_parameter.p
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_p = _symbols[offset + 3];
					final ParDeclValue p = (ParDeclValue) _symbol_p.value;
					 l.add(p); return _symbol_l;
			}
			case 82: // actor_parameter = IDENTIFIER.id opt$actor_parameter_init_expression.e
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					 return new Symbol(new ParDeclValue((String)id.value, null));
			}
			case 83: // actor_parameter = type.t IDENTIFIER.id opt$actor_parameter_init_expression.e
			{
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol id = _symbols[offset + 2];
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expression e = (Expression) _symbol_e.value;
					 return new Symbol(new ParDeclValue((String)id.value, t));
			}
			case 84: // actor_parameter_init_expression = EQ expression.e
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					 return _symbol_e;
			}
			case 85: // qual_id = IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 1];
					 ArrayList l = new ArrayList(); l.add(id.value); return new Symbol(l);
			}
			case 86: // qual_id = IDENTIFIER.id DOT qual_id.l
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_l = _symbols[offset + 3];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, id.value); return _symbol_l;
			}
			case 87: // decl_list = decl.d
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 ArrayList l = new ArrayList(); l.add(d); return new Symbol(l);
			}
			case 88: // decl_list = decl_list.l COMMA decl.d
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_d = _symbols[offset + 3];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 l.add(d); return _symbol_l;
			}
			case 89: // decl_block = VAR decl_list.d
			{
					final Symbol _symbol_d = _symbols[offset + 2];
					final ArrayList d = (ArrayList) _symbol_d.value;
					 return _symbol_d;
			}
			case 90: // decl_block_opt = 
			{
					 return new Symbol(new ArrayList());
			}
			case 91: // decl_block_opt = VAR decl_list.d
			{
					final Symbol _symbol_d = _symbols[offset + 2];
					final ArrayList d = (ArrayList) _symbol_d.value;
					 return _symbol_d;
			}
			case 92: // decl = var_decl.d
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 return _symbol_d;
			}
			case 93: // decl = fun_decl.d
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 return _symbol_d;
			}
			case 94: // decl = proc_decl.d
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final DeclVar d = (DeclVar) _symbol_d.value;
					 return _symbol_d;
			}
			case 95: // var_decl = MUTABLE var_name_type.v
			{
					final Symbol _symbol_v = _symbols[offset + 2];
					final DeclVar v = (DeclVar) _symbol_v.value;
					 return new Symbol(new DeclVar(v.getType(), v.getName(), null, null, true));
			}
			case 96: // var_decl = MUTABLE var_name_type.v EQ expression.init
			{
					final Symbol _symbol_v = _symbols[offset + 2];
					final DeclVar v = (DeclVar) _symbol_v.value;
					final Symbol _symbol_init = _symbols[offset + 4];
					final Expression init = (Expression) _symbol_init.value;
					 return new Symbol(new DeclVar(v.getType(), v.getName(), null, init, false));
			}
			case 97: // var_decl = MUTABLE var_name_type.v EQCOLON expression.init
			{
					final Symbol _symbol_v = _symbols[offset + 2];
					final DeclVar v = (DeclVar) _symbol_v.value;
					final Symbol _symbol_init = _symbols[offset + 4];
					final Expression init = (Expression) _symbol_init.value;
					 return new Symbol(new DeclVar(v.getType(), v.getName(), null, init, true));
			}
			case 98: // var_decl = var_name_type.v
			{
					final Symbol _symbol_v = _symbols[offset + 1];
					final DeclVar v = (DeclVar) _symbol_v.value;
					 return new Symbol(new DeclVar(v.getType(), v.getName(), null, null, true));
			}
			case 99: // var_decl = var_name_type.v EQ expression.init
			{
					final Symbol _symbol_v = _symbols[offset + 1];
					final DeclVar v = (DeclVar) _symbol_v.value;
					final Symbol _symbol_init = _symbols[offset + 3];
					final Expression init = (Expression) _symbol_init.value;
					 return new Symbol(new DeclVar(v.getType(), v.getName(), null, init, false));
			}
			case 100: // var_decl = var_name_type.v COLONEQ expression.init
			{
					final Symbol _symbol_v = _symbols[offset + 1];
					final DeclVar v = (DeclVar) _symbol_v.value;
					final Symbol _symbol_init = _symbols[offset + 3];
					final Expression init = (Expression) _symbol_init.value;
					 return new Symbol(new DeclVar(v.getType(), v.getName(), null, init, true));
			}
			case 101: // var_name_type = IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 1];
					 return new Symbol(new DeclVar(null, (String)id.value, null));
			}
			case 102: // var_name_type = type.type IDENTIFIER.id
			{
					final Symbol _symbol_type = _symbols[offset + 1];
					final TypeExpr type = (TypeExpr) _symbol_type.value;
					final Symbol id = _symbols[offset + 2];
					 return new Symbol(new DeclVar(type, (String)id.value, null));
			}
			case 103: // fun_decl = FUNCTION IDENTIFIER.id lambda_expr_body.lambda
			{
					final Symbol id = _symbols[offset + 2];
					final Symbol _symbol_lambda = _symbols[offset + 3];
					final ExprLambda lambda = (ExprLambda) _symbol_lambda.value;
					 return new Symbol(new DeclVar(null, (String)id.value, null, lambda, false));
			}
			case 104: // proc_decl = PROCEDURE IDENTIFIER.id procedure_expr_body.body
			{
					final Symbol id = _symbols[offset + 2];
					final Symbol _symbol_body = _symbols[offset + 3];
					final ExprProc body = (ExprProc) _symbol_body.value;
					 return new Symbol(new DeclVar(null, (String)id.value, null, body, false));
			}
			case 105: // port_decl = IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 1];
					 return new Symbol(new AtomicPortDecl((String)id.value, null));
			}
			case 106: // port_decl = type.type IDENTIFIER.id
			{
					final Symbol _symbol_type = _symbols[offset + 1];
					final TypeExpr type = (TypeExpr) _symbol_type.value;
					final Symbol id = _symbols[offset + 2];
					 return new Symbol(new AtomicPortDecl((String)id.value, type));
			}
			case 107: // port_decl = MULTI IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 2];
					 return new Symbol(new AtomicPortDecl((String)id.value, null));
			}
			case 108: // port_decl = MULTI type.type IDENTIFIER.id
			{
					final Symbol _symbol_type = _symbols[offset + 2];
					final TypeExpr type = (TypeExpr) _symbol_type.value;
					final Symbol id = _symbols[offset + 3];
					 return new Symbol(new AtomicPortDecl((String)id.value, type));
			}
			case 109: // port_decl_list_opt = 
			{
					 return new Symbol(new CompositePortDecl());
			}
			case 110: // port_decl_list_opt = port_decl_list.l
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final CompositePortDecl l = (CompositePortDecl) _symbol_l.value;
					 return _symbol_l;
			}
			case 111: // port_decl_list = port_decl.port_decl
			{
					final Symbol _symbol_port_decl = _symbols[offset + 1];
					final PortDecl port_decl = (PortDecl) _symbol_port_decl.value;
					 CompositePortDecl l = new CompositePortDecl(); l.addChild(port_decl); return new Symbol(l);
			}
			case 112: // port_decl_list = port_decl_list.l COMMA port_decl.d
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final CompositePortDecl l = (CompositePortDecl) _symbol_l.value;
					final Symbol _symbol_d = _symbols[offset + 3];
					final PortDecl d = (PortDecl) _symbol_d.value;
					 l.addChild(d); return _symbol_l;
			}
			case 113: // type_bound = LT type.type
			{
					final Symbol _symbol_type = _symbols[offset + 2];
					final TypeExpr type = (TypeExpr) _symbol_type.value;
					 return _symbol_type;
			}
			case 114: // type_bound_opt = 
			{
					 return new Symbol(null);
			}
			case 115: // type_bound_opt = type_bound.n
			{
					final Symbol _symbol_n = _symbols[offset + 1];
					final TypeExpr n = (TypeExpr) _symbol_n.value;
					 return _symbol_n;
			}
			case 116: // type_parameter = IDENTIFIER.id type_bound_opt.type_bound
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_type_bound = _symbols[offset + 2];
					final TypeExpr type_bound = (TypeExpr) _symbol_type_bound.value;
					 return new Symbol(new ParDeclType((String)id.value));
			}
			case 119: // type_parameter_block = LBRACK opt$type_parameter_list.l RBRACK
			{
					final Symbol _symbol_l = _symbols[offset + 2];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 return _symbol_l;
			}
			case 120: // type_parameter_list = type_parameter.tp
			{
					final Symbol _symbol_tp = _symbols[offset + 1];
					final ParDeclType tp = (ParDeclType) _symbol_tp.value;
					 ArrayList l = new ArrayList(); l.add(tp); return new Symbol(l);
			}
			case 121: // type_parameter_list = type_parameter_list.l COMMA type_parameter.tp
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_tp = _symbols[offset + 3];
					final ParDeclType tp = (ParDeclType) _symbol_tp.value;
					 l.add(tp); return _symbol_l;
			}
			case 122: // type_list = type.t
			{
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					 ArrayList l = new ArrayList(); l.add(t); return new Symbol(l);
			}
			case 123: // type_list = type_list.l COMMA type.t
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					 l.add(t); return _symbol_l;
			}
			case 124: // type = IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 1];
					 return new Symbol(new TypeExpr((String)id.value));
			}
			case 127: // type = IDENTIFIER.id LBRACK opt$type_list.t RBRACK
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_t = _symbols[offset + 3];
					final ArrayList t = (ArrayList) _symbol_t.value;
					 return new Symbol(t==null ? new TypeExpr((String)id.value) : new TypeExpr((String)id.value, (TypeExpr[])t.toArray(new TypeExpr[t.size()])));
			}
			case 130: // type = IDENTIFIER.id LPAREN opt$type_attribute_list.attributes RPAREN
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_attributes = _symbols[offset + 3];
					final ArrayList attributes = (ArrayList) _symbol_attributes.value;
					 Map<String,Expression> valueParameters = new java.util.HashMap();
                                                                   Map<String,TypeExpr> typeParameters = new java.util.HashMap();
                                                                   for(Map.Entry map : (ArrayList<Map.Entry>)attributes){
                                                                     if(map.getValue() instanceof Expression){
                                                                       valueParameters.put((String)map.getKey(), (Expression)map.getValue());
                                                                     } else {
                                                                       typeParameters.put((String)map.getKey(), (TypeExpr)map.getValue());
                                                                     }
                                                                   }
                                                                   return new Symbol(new TypeExpr((String)id.value, typeParameters, valueParameters));
			}
			case 131: // type = LBRACK opt$type_list.param EDGE type.result_type RBRACK
			{
					final Symbol _symbol_param = _symbols[offset + 2];
					final ArrayList param = (ArrayList) _symbol_param.value;
					final Symbol _symbol_result_type = _symbols[offset + 4];
					final TypeExpr result_type = (TypeExpr) _symbol_result_type.value;
					 return new Symbol(null);
			}
			case 132: // type = LBRACK opt$type_list.param EDGE RBRACK
			{
					final Symbol _symbol_param = _symbols[offset + 2];
					final ArrayList param = (ArrayList) _symbol_param.value;
					 return new Symbol(null);
			}
			case 133: // type_attribute_list = type_attribute.t
			{
					final Symbol _symbol_t = _symbols[offset + 1];
					final Map.Entry t = (Map.Entry) _symbol_t.value;
					 ArrayList l = new ArrayList(); l.add(t); return new Symbol(l);
			}
			case 134: // type_attribute_list = type_attribute_list.l COMMA type_attribute.t
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Map.Entry t = (Map.Entry) _symbol_t.value;
					 l.add(t); return _symbol_l;
			}
			case 135: // type_attribute = IDENTIFIER.id COLON type.type
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_type = _symbols[offset + 3];
					final TypeExpr type = (TypeExpr) _symbol_type.value;
					 return new Symbol(new AbstractMap.SimpleEntry((String)id.value, type));
			}
			case 136: // type_attribute = IDENTIFIER.id EQ expression.e
			{
					final Symbol id = _symbols[offset + 1];
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expression e = (Expression) _symbol_e.value;
					 return new Symbol(new AbstractMap.SimpleEntry((String)id.value, e));
			}
			case 137: // edge_type = EDGE type.t
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					 return _symbol_t;
			}
			case 142: // procedure_expr_body = LPAREN opt$formal_parameter_list.param RPAREN opt$decl_block.decl stmt_block_opt.body end_proc
			{
					final Symbol _symbol_param = _symbols[offset + 2];
					final ArrayList param = (ArrayList) _symbol_param.value;
					final Symbol _symbol_decl = _symbols[offset + 4];
					final ArrayList decl = (ArrayList) _symbol_decl.value;
					final Symbol _symbol_body = _symbols[offset + 5];
					final ArrayList body = (ArrayList) _symbol_body.value;
					 return new Symbol(new ExprProc(new ParDeclType[0], 
                                                                                                                    param==null ? new ParDeclValue[0] : (ParDeclValue[])param.toArray(new ParDeclValue[param.size()]),
                                                                                                                    new DeclType[0],
                                                                                                                    decl==null ? new DeclVar[0] : (DeclVar[])decl.toArray(new DeclVar[decl.size()]),
                                                                                                                    (Statement[])body.toArray(new Statement[body.size()])));
			}
			case 143: // stmt_block_opt = 
			{
					 return new Symbol(new ArrayList());
			}
			case 144: // stmt_block_opt = do_begin statement_list_opt.s
			{
					final Symbol _symbol_s = _symbols[offset + 2];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return _symbol_s;
			}
			case 145: // lambda_expr_body = LPAREN opt$formal_parameter_list.param RPAREN expression.body end_lambda
			{
					final Symbol _symbol_param = _symbols[offset + 2];
					final ArrayList param = (ArrayList) _symbol_param.value;
					final Symbol _symbol_body = _symbols[offset + 4];
					final Expression body = (Expression) _symbol_body.value;
					 return new Symbol(new ExprLambda(new ParDeclType[0],
                                             param==null ? new ParDeclValue[0] : (ParDeclValue[])param.toArray(new ParDeclValue[param.size()]),
                                             new DeclType[0], 
                                             new DeclVar[0],
                                             body,
                                             null));
			}
			case 146: // lambda_expr_body = LPAREN opt$formal_parameter_list.param RPAREN opt$decl_block.decl COLON expression.body end_lambda
			{
					final Symbol _symbol_param = _symbols[offset + 2];
					final ArrayList param = (ArrayList) _symbol_param.value;
					final Symbol _symbol_decl = _symbols[offset + 4];
					final ArrayList decl = (ArrayList) _symbol_decl.value;
					final Symbol _symbol_body = _symbols[offset + 6];
					final Expression body = (Expression) _symbol_body.value;
					 return new Symbol(new ExprLambda(new ParDeclType[0],
                                             param==null ? new ParDeclValue[0] : (ParDeclValue[])param.toArray(new ParDeclValue[param.size()]),
                                             new DeclType[0],
                                             decl==null ? new DeclVar[0] : (DeclVar[])decl.toArray(new DeclVar[decl.size()]),
                                             body,
                                             null));
			}
			case 147: // lambda_expr_body = LPAREN opt$formal_parameter_list.param RPAREN edge_type.t opt$decl_block.decl COLON expression.body end_lambda
			{
					final Symbol _symbol_param = _symbols[offset + 2];
					final ArrayList param = (ArrayList) _symbol_param.value;
					final Symbol _symbol_t = _symbols[offset + 4];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_decl = _symbols[offset + 5];
					final ArrayList decl = (ArrayList) _symbol_decl.value;
					final Symbol _symbol_body = _symbols[offset + 7];
					final Expression body = (Expression) _symbol_body.value;
					 return new Symbol(new ExprLambda(new ParDeclType[0],
                                             param==null ? new ParDeclValue[0] : (ParDeclValue[])param.toArray(new ParDeclValue[param.size()]),
                                             new DeclType[0],
                                             decl==null ? new DeclVar[0] : (DeclVar[])decl.toArray(new DeclVar[decl.size()]),
                                             body,
                                             t));
			}
			case 148: // map_list = map_entry.m
			{
					final Symbol _symbol_m = _symbols[offset + 1];
					final Map.Entry m = (Map.Entry) _symbol_m.value;
					 ArrayList l = new ArrayList(); l.add(m); return new Symbol(l);
			}
			case 149: // map_list = map_list.l COMMA map_entry.m
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_m = _symbols[offset + 3];
					final Map.Entry m = (Map.Entry) _symbol_m.value;
					 l.add(m); return _symbol_l;
			}
			case 150: // map_entry = expression.e1 ARROW expression.e2
			{
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expression e1 = (Expression) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expression e2 = (Expression) _symbol_e2.value;
					 return new Symbol(new AbstractMap.SimpleEntry(e1, e2));
			}
			case 151: // tail = BAR expression.e
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					 return _symbol_e;
			}
			case 152: // expression_list = expression.e
			{
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expression e = (Expression) _symbol_e.value;
					 ArrayList l = new ArrayList(); l.add(e); return new Symbol(l);
			}
			case 153: // expression_list = expression_list.l COMMA expression.e
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expression e = (Expression) _symbol_e.value;
					 l.add(e); return _symbol_l;
			}
			case 154: // expression_list_opt = 
			{
					 return new Symbol(new ArrayList());
			}
			case 155: // expression_list_opt = expression_list.n
			{
					final Symbol _symbol_n = _symbols[offset + 1];
					final ArrayList n = (ArrayList) _symbol_n.value;
					 return _symbol_n;
			}
			case 158: // method_invocation = simple_expression.function LPAREN opt$expression_list.args RPAREN
			{
					final Symbol _symbol_function = _symbols[offset + 1];
					final Expression function = (Expression) _symbol_function.value;
					final Symbol _symbol_args = _symbols[offset + 3];
					final ArrayList args = (ArrayList) _symbol_args.value;
					 return new Symbol(new ExprApplication(function, args==null ? new Expression[0] : (Expression[])args.toArray(new Expression[args.size()])));
			}
			case 159: // literal = INTEGER_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litInteger, ((String)txt.value)));
			}
			case 160: // literal = LONG_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litInteger, ((String)txt.value)));
			}
			case 161: // literal = FLOATING_POINT_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litInteger, ((String)txt.value)));
			}
			case 162: // literal = DOUBLE_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litReal, ((String)txt.value)));
			}
			case 163: // literal = TRUE_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litTrue, ((String)txt.value)));
			}
			case 164: // literal = FALSE_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litFalse, ((String)txt.value)));
			}
			case 165: // literal = CHARACTER_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litChar, ((String)txt.value)));
			}
			case 166: // literal = STRING_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litString, ((String)txt.value)));
			}
			case 167: // literal = NULL_LITERAL.txt
			{
					final Symbol txt = _symbols[offset + 1];
					 return new Symbol(new ExprLiteral(ExprLiteral.litNull, ((String)txt.value)));
			}
			case 168: // primary = literal.l
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ExprLiteral l = (ExprLiteral) _symbol_l.value;
					 return _symbol_l;
			}
			case 169: // primary = LPAREN expression.e RPAREN
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					 return new ParenthesSymbol(_symbol_e);
			}
			case 170: // primary = LPAREN.start expression.e DOUBLECOLON type.t RPAREN
			{
					final Symbol start = _symbols[offset + 1];
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_t = _symbols[offset + 4];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					 parseProblems.add("Type assertion is not supported. Assertion is ignored at " + Symbol.getLine(start.getStart()) + ", " + Symbol.getColumn(start.getStart()));
			}
			case 171: // simple_expression = primary.p
			{
					final Symbol _symbol_p = _symbols[offset + 1];
					final Expression p = (Expression) _symbol_p.value;
					 return _symbol_p;
			}
			case 172: // simple_expression = IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 1];
					 return new Symbol(new ExprVariable((String)id.value));
			}
			case 173: // simple_expression = OLD IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 2];
					 return new Symbol(new ExprVariable((String)id.value));
			}
			case 174: // simple_expression = method_invocation.m
			{
					final Symbol _symbol_m = _symbols[offset + 1];
					final ExprApplication m = (ExprApplication) _symbol_m.value;
					 return _symbol_m;
			}
			case 175: // simple_expression = IF expression.c THEN expression.e1 ELSE expression.e2 END
			{
					final Symbol _symbol_c = _symbols[offset + 2];
					final Expression c = (Expression) _symbol_c.value;
					final Symbol _symbol_e1 = _symbols[offset + 4];
					final Expression e1 = (Expression) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 6];
					final Expression e2 = (Expression) _symbol_e2.value;
					 return new Symbol(new ExprIf(c, e1, e2));
			}
			case 176: // simple_expression = LBRACE expression_list_opt.e RBRACE
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					 return new Symbol(new ExprSet((Expression[])e.toArray(new Expression[e.size()])));
			}
			case 177: // simple_expression = LBRACE expression_list_opt.e COLON for_generator_list.l RBRACE
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					final Symbol _symbol_l = _symbols[offset + 4];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 return new Symbol(new ExprSet((Expression[])e.toArray(new Expression[e.size()]), (GeneratorFilter[])l.toArray(new GeneratorFilter[l.size()])));
			}
			case 178: // simple_expression = LBRACK expression_list_opt.e RBRACK
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					 return new Symbol(new ExprList((Expression[])e.toArray(new Expression[e.size()])));
			}
			case 179: // simple_expression = LBRACK expression_list_opt.e tail.tail RBRACK
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					final Symbol _symbol_tail = _symbols[offset + 3];
					final Expression tail = (Expression) _symbol_tail.value;
					 return new Symbol(new ExprList((Expression[])e.toArray(new Expression[e.size()])));
			}
			case 180: // simple_expression = LBRACK expression_list_opt.e COLON for_generator_list.l RBRACK
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					final Symbol _symbol_l = _symbols[offset + 4];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 return new Symbol(new ExprList((Expression[])e.toArray(new Expression[e.size()]), (GeneratorFilter[])l.toArray(new GeneratorFilter[l.size()])));
			}
			case 181: // simple_expression = LBRACK expression_list_opt.e COLON for_generator_list.l tail.tail RBRACK
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final ArrayList e = (ArrayList) _symbol_e.value;
					final Symbol _symbol_l = _symbols[offset + 4];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_tail = _symbols[offset + 5];
					final Expression tail = (Expression) _symbol_tail.value;
					 return new Symbol(new ExprList((Expression[])e.toArray(new Expression[e.size()]), (GeneratorFilter[])l.toArray(new GeneratorFilter[l.size()])));
			}
			case 184: // simple_expression = MAP LBRACE opt$map_list.m RBRACE
			{
					final Symbol _symbol_m = _symbols[offset + 3];
					final ArrayList m = (ArrayList) _symbol_m.value;
					 return new Symbol(new ExprMap(m==null? new java.util.Map.Entry[0] : 
                                                                                                              (java.util.Map.Entry<Expression,Expression>[])m.toArray(new java.util.Map.Entry[m.size()])));
			}
			case 185: // simple_expression = MAP LBRACE opt$map_list.m COLON for_generator_list.generators RBRACE
			{
					final Symbol _symbol_m = _symbols[offset + 3];
					final ArrayList m = (ArrayList) _symbol_m.value;
					final Symbol _symbol_generators = _symbols[offset + 5];
					final ArrayList generators = (ArrayList) _symbol_generators.value;
					 return new Symbol(new ExprMap(m==null? new java.util.Map.Entry[0] : 
                                                                                                              (java.util.Map.Entry<Expression,Expression>[])m.toArray(new java.util.Map.Entry[m.size()]), 
                                                                                                              (GeneratorFilter[])generators.toArray(new GeneratorFilter[generators.size()])));
			}
			case 186: // simple_expression = LET decl_list.l COLON expression.e end_let
			{
					final Symbol _symbol_l = _symbols[offset + 2];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					 return new Symbol(new ExprLet(new DeclType[0], (DeclVar[])l.toArray(new DeclVar[l.size()]), e));
			}
			case 187: // simple_expression = LAMBDA lambda_expr_body.lambda
			{
					final Symbol _symbol_lambda = _symbols[offset + 2];
					final ExprLambda lambda = (ExprLambda) _symbol_lambda.value;
					 return _symbol_lambda;
			}
			case 188: // simple_expression = CONST LAMBDA lambda_expr_body.lambda
			{
					final Symbol _symbol_lambda = _symbols[offset + 3];
					final ExprLambda lambda = (ExprLambda) _symbol_lambda.value;
					 return _symbol_lambda;
			}
			case 189: // simple_expression = PROC procedure_expr_body.p
			{
					final Symbol _symbol_p = _symbols[offset + 2];
					final ExprProc p = (ExprProc) _symbol_p.value;
					 return _symbol_p;
			}
			case 190: // unary_expression = simple_expression.e
			{
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expression e = (Expression) _symbol_e.value;
					 return _symbol_e;
			}
			case 191: // unary_expression = operator.operator unary_expression.expr
			{
					final Symbol _symbol_operator = _symbols[offset + 1];
					final String operator = (String) _symbol_operator.value;
					final Symbol _symbol_expr = _symbols[offset + 2];
					final Expression expr = (Expression) _symbol_expr.value;
					 return new Symbol(new ExprUnaryOp(operator, expr));
			}
			case 192: // indexing_expression = unary_expression.e
			{
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expression e = (Expression) _symbol_e.value;
					 return _symbol_e;
			}
			case 193: // indexing_expression = indexing_expression.p LBRACK expression_list.l RBRACK
			{
					final Symbol _symbol_p = _symbols[offset + 1];
					final Expression p = (Expression) _symbol_p.value;
					final Symbol _symbol_l = _symbols[offset + 3];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 return new Symbol(new ExprIndexer(p, (Expression[])l.toArray(new Expression[l.size()])));
			}
			case 194: // indexing_expression = indexing_expression.p DOT IDENTIFIER.id
			{
					final Symbol _symbol_p = _symbols[offset + 1];
					final Expression p = (Expression) _symbol_p.value;
					final Symbol id = _symbols[offset + 3];
					 return new Symbol(new ExprEntry((String)id.value, p));
			}
			case 195: // expression = indexing_expression.e
			{
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expression e = (Expression) _symbol_e.value;
					 return _symbol_e;
			}
			case 196: // expression = expression.arg1 operator.operator indexing_expression.arg2
			{
					final Symbol _symbol_arg1 = _symbols[offset + 1];
					final Expression arg1 = (Expression) _symbol_arg1.value;
					final Symbol _symbol_operator = _symbols[offset + 2];
					final String operator = (String) _symbol_operator.value;
					final Symbol _symbol_arg2 = _symbols[offset + 3];
					final Expression arg2 = (Expression) _symbol_arg2.value;
					 String[] operators;
                                                               Expression[] operands;
                                                               boolean arg1IsPar = _symbol_arg1 instanceof ParenthesSymbol;
                                                               if((arg1 instanceof ExprBinaryOp) && !(arg1IsPar)){
                                                                 ExprBinaryOp expr = (ExprBinaryOp)arg1;
                                                                 operators = Arrays.copyOf(expr.getOperations(), expr.getOperations().length + 1);
                                                                 operators[operators.length-1] = operator;
                                                                 operands = Arrays.copyOf(expr.getOperands(), expr.getOperands().length + 1);
                                                                 operands[operands.length-1] = arg2;
                                                               } else {
                                                                 operators = new String[1];
                                                                 operators[0] = operator;
                                                                 operands = new Expression[2];
                                                                 operands[0] = arg1;
                                                                 operands[1] = arg2;
                                                               }
                                                               return new Symbol(new ExprBinaryOp(operators, operands));
			}
			case 197: // operator = OPERATOR.op
			{
					final Symbol op = _symbols[offset + 1];
					 return op;
			}
			case 198: // operator = EQ.op
			{
					final Symbol op = _symbols[offset + 1];
					 return op;
			}
			case 199: // operator = IN.op
			{
					final Symbol op = _symbols[offset + 1];
					 return op;
			}
			case 200: // operator = GT.op
			{
					final Symbol op = _symbols[offset + 1];
					 return op;
			}
			case 201: // operator = MULT.op
			{
					final Symbol op = _symbols[offset + 1];
					 return op;
			}
			case 202: // formal_parameter = IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 1];
					 return new Symbol(new ParDeclValue((String)id.value, null));
			}
			case 203: // formal_parameter = type.t IDENTIFIER.id
			{
					final Symbol _symbol_t = _symbols[offset + 1];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol id = _symbols[offset + 2];
					 return new Symbol(new ParDeclValue((String)id.value, t));
			}
			case 204: // formal_parameter_list = formal_parameter.p
			{
					final Symbol _symbol_p = _symbols[offset + 1];
					final ParDeclValue p = (ParDeclValue) _symbol_p.value;
					 ArrayList l = new ArrayList(); l.add(p); return new Symbol(l);
			}
			case 205: // formal_parameter_list = formal_parameter_list.l COMMA formal_parameter.p
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_p = _symbols[offset + 3];
					final ParDeclValue p = (ParDeclValue) _symbol_p.value;
					 l.add(p);  return _symbol_l;
			}
			case 206: // statement = expression.lhs COLONEQ expression.value SEMICOLON
			{
					final Symbol _symbol_lhs = _symbols[offset + 1];
					final Expression lhs = (Expression) _symbol_lhs.value;
					final Symbol _symbol_value = _symbols[offset + 3];
					final Expression value = (Expression) _symbol_value.value;
					 if(lhs instanceof ExprVariable){
                                                           return new Symbol(new StmtAssignment(((ExprVariable)lhs).getName(), value)); 
                                                         } else if(lhs instanceof ExprIndexer){
                                                             ExprIndexer indexer = (ExprIndexer)lhs;
                                                             if(indexer.getStructure() instanceof ExprVariable){
                                                               return new Symbol(new StmtAssignment(((ExprVariable)indexer.getStructure()).getName(), value, indexer.getLocation())); 
                                                             }
                                                         } else if(lhs instanceof ExprEntry){
                                                             ExprEntry field = (ExprEntry)lhs;
                                                             if(field.getEnclosingExpr() instanceof ExprVariable){
                                                               return new Symbol(new StmtAssignment(((ExprVariable)field.getEnclosingExpr()).getName(), value, field.getName())); 
                                                             }
                                                         }
                                                         newError("Illegal left hand sign of assignment.", _symbol_lhs);
                                                         return new Symbol(new StmtAssignment("illegal", value));
			}
			case 207: // statement = method_invocation.m SEMICOLON
			{
					final Symbol _symbol_m = _symbols[offset + 1];
					final ExprApplication m = (ExprApplication) _symbol_m.value;
					 return new Symbol(new StmtCall(m.getFunction(), m.getArgs()));
			}
			case 208: // statement = BEGIN statement_list_opt.s END
			{
					final Symbol _symbol_s = _symbols[offset + 2];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Symbol(new StmtBlock(new DeclType[0], new DeclVar[0], (Statement[])s.toArray(new Statement[s.size()])));
			}
			case 209: // statement = BEGIN VAR decl_list.d DO statement_list_opt.s END
			{
					final Symbol _symbol_d = _symbols[offset + 3];
					final ArrayList d = (ArrayList) _symbol_d.value;
					final Symbol _symbol_s = _symbols[offset + 5];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Symbol(new StmtBlock(new DeclType[0], (DeclVar[])d.toArray(new DeclVar[d.size()]), (Statement[])s.toArray(new Statement[s.size()])));
			}
			case 210: // statement = IF expression.e THEN statement_list_opt.s end_if
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_s = _symbols[offset + 4];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Symbol(new StmtIf(e, new StmtBlock(null, null, (Statement[])s.toArray(new Statement[s.size()])), null));
			}
			case 211: // statement = IF expression.e THEN statement_list_opt.s1 ELSE statement_list_opt.s2 end_if
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_s1 = _symbols[offset + 4];
					final ArrayList s1 = (ArrayList) _symbol_s1.value;
					final Symbol _symbol_s2 = _symbols[offset + 6];
					final ArrayList s2 = (ArrayList) _symbol_s2.value;
					 return new Symbol(new StmtIf(e, 
                                                                                                                 new StmtBlock(null, null, (Statement[])s1.toArray(new Statement[s1.size()])),
                                                                                                                 new StmtBlock(null, null, (Statement[])s2.toArray(new Statement[s2.size()]))));
			}
			case 212: // statement = WHILE expression.e decl_block_opt.d DO statement_list_opt.s end_while
			{
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_d = _symbols[offset + 3];
					final ArrayList d = (ArrayList) _symbol_d.value;
					final Symbol _symbol_s = _symbols[offset + 5];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Symbol(new StmtWhile(e, new StmtBlock(new DeclType[0],
                                                                                                                              (DeclVar[])d.toArray(new DeclVar[d.size()]),
                                                                                                                              (Statement[])s.toArray(new Statement[s.size()]))));
			}
			case 216: // statement = for_generator_list.g DO statement_list_opt.s end_foreach
			{
					final Symbol _symbol_g = _symbols[offset + 1];
					final ArrayList g = (ArrayList) _symbol_g.value;
					final Symbol _symbol_s = _symbols[offset + 3];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Symbol(new StmtForeach((GeneratorFilter[])g.toArray(new GeneratorFilter[g.size()]),
                                                                                                               new StmtBlock(new DeclType[0], new DeclVar[0], (Statement[])s.toArray(new Statement[s.size()]))));
			}
			case 217: // statement = for_generator_list.g decl_block.d DO statement_list_opt.s end_foreach
			{
					final Symbol _symbol_g = _symbols[offset + 1];
					final ArrayList g = (ArrayList) _symbol_g.value;
					final Symbol _symbol_d = _symbols[offset + 2];
					final ArrayList d = (ArrayList) _symbol_d.value;
					final Symbol _symbol_s = _symbols[offset + 4];
					final ArrayList s = (ArrayList) _symbol_s.value;
					 return new Symbol(new StmtForeach((GeneratorFilter[])g.toArray(new GeneratorFilter[g.size()]),
                                                                                                               new StmtBlock(new DeclType[0], (DeclVar[])d.toArray(new DeclVar[d.size()]), (Statement[])s.toArray(new Statement[s.size()]))));
			}
			case 218: // choose_generator_list = CHOOSE generator_variable_list.vars IN expression.e
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(null, vars, e, null)); return new Symbol(l);
			}
			case 219: // choose_generator_list = CHOOSE type.t generator_variable_list.vars IN expression.e
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(t, vars, e, null)); return new Symbol(l);
			}
			case 220: // choose_generator_list = CHOOSE generator_variable_list.vars IN expression.e COMMA expression_list.filters
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 6];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(null, vars, e, filters)); return new Symbol(l);
			}
			case 221: // choose_generator_list = CHOOSE type.t generator_variable_list.vars IN expression.e COMMA expression_list.filters
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 7];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(t, vars, e, filters)); return new Symbol(l);
			}
			case 222: // choose_generator_list = CHOOSE generator_variable_list.vars IN expression.e COMMA choose_generator_list.l
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_l = _symbols[offset + 6];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(null, vars, e, null)); return _symbol_l;
			}
			case 223: // choose_generator_list = CHOOSE type.t generator_variable_list.vars IN expression.e COMMA choose_generator_list.l
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_l = _symbols[offset + 7];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(t, vars, e, null)); return _symbol_l;
			}
			case 224: // choose_generator_list = CHOOSE generator_variable_list.vars IN expression.e COMMA expression_list.filters COMMA choose_generator_list.l
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 6];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					final Symbol _symbol_l = _symbols[offset + 8];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(null, vars, e, filters)); return _symbol_l;
			}
			case 225: // choose_generator_list = CHOOSE type.t generator_variable_list.vars IN expression.e COMMA expression_list.filters COMMA choose_generator_list.l
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 7];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					final Symbol _symbol_l = _symbols[offset + 9];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(t, vars, e, filters)); return _symbol_l;
			}
			case 226: // for_generator_list = for_foreach generator_variable_list.vars IN expression.e
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(null, vars, e, null)); return new Symbol(l);
			}
			case 227: // for_generator_list = for_foreach type.t generator_variable_list.vars IN expression.e
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(t, vars, e, null)); return new Symbol(l);
			}
			case 228: // for_generator_list = for_foreach generator_variable_list.vars IN expression.e COMMA expression_list.filters
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 6];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(null, vars, e, filters)); return new Symbol(l);
			}
			case 229: // for_generator_list = for_foreach type.t generator_variable_list.vars IN expression.e COMMA expression_list.filters
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 7];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					 ArrayList l = new ArrayList(); l.add(makeGeneratorFilter(t, vars, e, filters)); return new Symbol(l);
			}
			case 230: // for_generator_list = for_foreach generator_variable_list.vars IN expression.e COMMA for_generator_list.l
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_l = _symbols[offset + 6];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(null, vars, e, null)); return _symbol_l;
			}
			case 231: // for_generator_list = for_foreach type.t generator_variable_list.vars IN expression.e COMMA for_generator_list.l
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_l = _symbols[offset + 7];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(t, vars, e, null)); return _symbol_l;
			}
			case 232: // for_generator_list = for_foreach generator_variable_list.vars IN expression.e COMMA expression_list.filters COMMA for_generator_list.l
			{
					final Symbol _symbol_vars = _symbols[offset + 2];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 4];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 6];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					final Symbol _symbol_l = _symbols[offset + 8];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(null, vars, e, filters)); return _symbol_l;
			}
			case 233: // for_generator_list = for_foreach type.t generator_variable_list.vars IN expression.e COMMA expression_list.filters COMMA for_generator_list.l
			{
					final Symbol _symbol_t = _symbols[offset + 2];
					final TypeExpr t = (TypeExpr) _symbol_t.value;
					final Symbol _symbol_vars = _symbols[offset + 3];
					final ArrayList vars = (ArrayList) _symbol_vars.value;
					final Symbol _symbol_e = _symbols[offset + 5];
					final Expression e = (Expression) _symbol_e.value;
					final Symbol _symbol_filters = _symbols[offset + 7];
					final ArrayList filters = (ArrayList) _symbol_filters.value;
					final Symbol _symbol_l = _symbols[offset + 9];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 l.add(0, makeGeneratorFilter(t, vars, e, filters)); return _symbol_l;
			}
			case 234: // generator_variable_list = IDENTIFIER.id
			{
					final Symbol id = _symbols[offset + 1];
					 ArrayList l = new ArrayList(); l.add(id); return new Symbol(l);
			}
			case 235: // generator_variable_list = generator_variable_list.l COMMA IDENTIFIER.id
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol id = _symbols[offset + 3];
					 l.add(id); return _symbol_l;
			}
			case 254: // statement_list_opt = 
			{
					 return new Symbol(new ArrayList());
			}
			case 255: // statement_list_opt = statement_list.l
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					 return _symbol_l;
			}
			case 256: // statement_list = statement.n
			{
					final Symbol _symbol_n = _symbols[offset + 1];
					final Statement n = (Statement) _symbol_n.value;
					 ArrayList l = new ArrayList(); l.add(n); return new Symbol(l);
			}
			case 257: // statement_list = statement_list.l statement.n
			{
					final Symbol _symbol_l = _symbols[offset + 1];
					final ArrayList l = (ArrayList) _symbol_l.value;
					final Symbol _symbol_n = _symbols[offset + 2];
					final Statement n = (Statement) _symbol_n.value;
					 l.add(n); return _symbol_l;
			}
			case 0: // opt$type_parameter_block = 
			case 2: // opt$actor_parameter_list = 
			case 6: // opt$lst$network_body_part = 
			case 8: // opt$SEMICOLON = 
			case 18: // opt$lst$network_decl = 
			case 26: // opt$lst$entity = 
			case 30: // opt$param_assign_list = 
			case 32: // opt$tool_attribute_block = 
			case 36: // opt$entity_expr_list = 
			case 47: // opt$lst$entity_statement = 
			case 56: // opt$lst$entity_indexing = 
			case 71: // opt$lst$tool_attribute = 
			case 80: // opt$actor_parameter_init_expression = 
			case 117: // opt$type_parameter_list = 
			case 125: // opt$type_list = 
			case 128: // opt$type_attribute_list = 
			case 138: // opt$formal_parameter_list = 
			case 140: // opt$decl_block = 
			case 156: // opt$expression_list = 
			case 182: // opt$map_list = 
			{
				return new Symbol(null);
			}
			case 1: // opt$type_parameter_block = type_parameter_block
			case 3: // opt$actor_parameter_list = actor_parameter_list
			case 7: // opt$lst$network_body_part = lst$network_body_part
			case 9: // opt$SEMICOLON = SEMICOLON
			case 19: // opt$lst$network_decl = lst$network_decl
			case 27: // opt$lst$entity = lst$entity
			case 31: // opt$param_assign_list = param_assign_list
			case 33: // opt$tool_attribute_block = tool_attribute_block
			case 37: // opt$entity_expr_list = entity_expr_list
			case 48: // opt$lst$entity_statement = lst$entity_statement
			case 57: // opt$lst$entity_indexing = lst$entity_indexing
			case 72: // opt$lst$tool_attribute = lst$tool_attribute
			case 76: // end_network = END
			case 77: // end_network = ENDNETWORK
			case 81: // opt$actor_parameter_init_expression = actor_parameter_init_expression
			case 118: // opt$type_parameter_list = type_parameter_list
			case 126: // opt$type_list = type_list
			case 129: // opt$type_attribute_list = type_attribute_list
			case 139: // opt$formal_parameter_list = formal_parameter_list
			case 141: // opt$decl_block = decl_block
			case 157: // opt$expression_list = expression_list
			case 183: // opt$map_list = map_list
			case 236: // for_foreach = FOREACH.FOREACH
			case 237: // for_foreach = FOR.FOR
			case 238: // do_begin = BEGIN.BEGIN
			case 239: // do_begin = DO.DO
			case 240: // end_choose = END.END
			case 241: // end_choose = ENDCHOOSE.ENDCHOOSE
			case 242: // end_foreach = END.END
			case 243: // end_foreach = ENDFOREACH.ENDFOREACH
			case 244: // end_if = END.END
			case 245: // end_if = ENDIF.ENDIF
			case 246: // end_lambda = END.END
			case 247: // end_lambda = ENDLAMBDA.ENDLAMBDA
			case 248: // end_let = END.END
			case 249: // end_let = ENDLET.ENDLET
			case 250: // end_proc = END.END
			case 251: // end_proc = ENDPROC.ENDPROC
			case 252: // end_while = END.END
			case 253: // end_while = ENDWHILE.ENDWHILE
			{
				return _symbols[offset + 1];
			}
			case 213: // statement = choose_generator_list.l decl_block_opt.do_v DO statement_list_opt.do_s end_choose
			{
				return _symbols[offset + 4];
			}
			case 214: // statement = choose_generator_list.l decl_block_opt.do_v DO statement_list_opt.do_s ELSE statement_list_opt.else_s end_choose
			{
				return _symbols[offset + 6];
			}
			case 215: // statement = choose_generator_list.l decl_block_opt.do_v DO statement_list_opt.do_s ELSE decl_block_opt.else_v DO statement_list_opt.else_s end_choose
			{
				return _symbols[offset + 8];
			}
			default:
				throw new IllegalArgumentException("unknown production #" + rule_num);
		}
	}
}
