/* The following code was generated by JFlex 1.4.3 on 2013-06-27 13:25 */

package net.opendf.parser.lth; // The generated parser will belong to package AST_CAL

import beaver.Symbol;
import beaver.Scanner;
import net.opendf.parser.lth.NlParser.Terminals; // The terminals are implicitly defined in the parser
import java.io.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2013-06-27 13:25 from the specification file
 * <tt>/Users/pera/workspace/dataflow/bin/generated/NlScanner.flex</tt>
 */
public final class NlScanner extends beaver.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\1\1\0\1\3\1\2\16\7\4\0\1\3\1\11"+
    "\1\25\1\11\1\12\2\11\1\24\1\61\1\62\1\5\1\23\1\70"+
    "\1\71\1\21\1\4\1\14\3\26\4\20\2\17\1\60\1\67\1\11"+
    "\1\13\1\72\2\11\3\16\1\57\1\22\1\56\5\6\1\55\13\6"+
    "\1\15\2\6\1\65\1\10\1\66\1\11\1\73\1\0\1\43\1\45"+
    "\1\41\1\50\1\30\1\51\1\46\1\47\1\36\1\6\1\35\1\44"+
    "\1\52\1\27\1\33\1\53\1\6\1\34\1\37\1\31\1\40\1\54"+
    "\1\32\1\74\1\42\1\6\1\63\1\11\1\64\1\11\41\7\2\0"+
    "\4\6\4\0\1\6\2\0\1\7\7\0\1\6\4\0\1\6\5\0"+
    "\21\6\1\12\5\6\1\0\37\6\1\0\u01ca\6\4\0\14\6\16\0"+
    "\5\6\7\0\1\6\1\0\1\6\21\0\160\7\5\6\1\0\2\6"+
    "\2\0\4\6\10\0\1\6\1\0\3\6\1\0\1\6\1\0\24\6"+
    "\1\0\123\6\1\0\213\6\1\0\5\7\2\0\236\6\11\0\46\6"+
    "\2\0\1\6\7\0\47\6\11\0\55\7\1\0\1\7\1\0\2\7"+
    "\1\0\2\7\1\0\1\7\10\0\33\6\5\0\3\6\15\0\4\7"+
    "\7\0\1\6\4\0\13\7\5\0\53\6\37\7\4\0\2\6\1\7"+
    "\143\6\1\0\1\6\10\7\1\0\6\7\2\6\2\7\1\0\4\7"+
    "\2\6\12\7\3\6\2\0\1\6\17\0\1\7\1\6\1\7\36\6"+
    "\33\7\2\0\131\6\13\7\1\6\16\0\12\7\41\6\11\7\2\6"+
    "\4\0\1\6\5\0\26\6\4\7\1\6\11\7\1\6\3\7\1\6"+
    "\5\7\22\0\31\6\3\7\244\0\4\7\66\6\3\7\1\6\22\7"+
    "\1\6\7\7\12\6\2\7\2\0\12\7\1\0\7\6\1\0\7\6"+
    "\1\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\1\6\3\0\4\6\2\0\1\7\1\6\7\7\2\0\2\7"+
    "\2\0\3\7\1\6\10\0\1\7\4\0\2\6\1\0\3\6\2\7"+
    "\2\0\12\7\4\6\7\0\1\6\5\0\3\7\1\0\6\6\4\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\2\6\1\0"+
    "\2\6\2\0\1\7\1\0\5\7\4\0\2\7\2\0\3\7\3\0"+
    "\1\7\7\0\4\6\1\0\1\6\7\0\14\7\3\6\1\7\13\0"+
    "\3\7\1\0\11\6\1\0\3\6\1\0\26\6\1\0\7\6\1\0"+
    "\2\6\1\0\5\6\2\0\1\7\1\6\10\7\1\0\3\7\1\0"+
    "\3\7\2\0\1\6\17\0\2\6\2\7\2\0\12\7\1\0\1\6"+
    "\17\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\2\6\1\0\5\6\2\0\1\7\1\6\7\7\2\0\2\7"+
    "\2\0\3\7\10\0\2\7\4\0\2\6\1\0\3\6\2\7\2\0"+
    "\12\7\1\0\1\6\20\0\1\7\1\6\1\0\6\6\3\0\3\6"+
    "\1\0\4\6\3\0\2\6\1\0\1\6\1\0\2\6\3\0\2\6"+
    "\3\0\3\6\3\0\14\6\4\0\5\7\3\0\3\7\1\0\4\7"+
    "\2\0\1\6\6\0\1\7\16\0\12\7\11\0\1\6\7\0\3\7"+
    "\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6"+
    "\3\0\1\6\7\7\1\0\3\7\1\0\4\7\7\0\2\7\1\0"+
    "\2\6\6\0\2\6\2\7\2\0\12\7\22\0\2\7\1\0\10\6"+
    "\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6\2\0\1\7"+
    "\1\6\7\7\1\0\3\7\1\0\4\7\7\0\2\7\7\0\1\6"+
    "\1\0\2\6\2\7\2\0\12\7\1\0\2\6\17\0\2\7\1\0"+
    "\10\6\1\0\3\6\1\0\51\6\2\0\1\6\7\7\1\0\3\7"+
    "\1\0\4\7\1\6\10\0\1\7\10\0\2\6\2\7\2\0\12\7"+
    "\12\0\6\6\2\0\2\7\1\0\22\6\3\0\30\6\1\0\11\6"+
    "\1\0\1\6\2\0\7\6\3\0\1\7\4\0\6\7\1\0\1\7"+
    "\1\0\10\7\22\0\2\7\15\0\60\6\1\7\2\6\7\7\4\0"+
    "\10\6\10\7\1\0\12\7\47\0\2\6\1\0\1\6\2\0\2\6"+
    "\1\0\1\6\2\0\1\6\6\0\4\6\1\0\7\6\1\0\3\6"+
    "\1\0\1\6\1\0\1\6\2\0\2\6\1\0\4\6\1\7\2\6"+
    "\6\7\1\0\2\7\1\6\2\0\5\6\1\0\1\6\1\0\6\7"+
    "\2\0\12\7\2\0\2\6\42\0\1\6\27\0\2\7\6\0\12\7"+
    "\13\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7\10\6\1\0"+
    "\44\6\4\0\24\7\1\0\2\7\5\6\13\7\1\0\44\7\11\0"+
    "\1\7\71\0\53\6\24\7\1\6\12\7\6\0\6\6\4\7\4\6"+
    "\3\7\1\6\3\7\2\6\7\7\3\6\4\7\15\6\14\7\1\6"+
    "\17\7\2\0\46\6\12\0\53\6\1\0\1\6\3\0\u0149\6\1\0"+
    "\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\51\6\1\0"+
    "\4\6\2\0\41\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0"+
    "\4\6\2\0\17\6\1\0\71\6\1\0\4\6\2\0\103\6\2\0"+
    "\3\7\40\0\20\6\20\0\125\6\14\0\u026c\6\2\0\21\6\1\0"+
    "\32\6\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6\3\7"+
    "\13\0\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0\3\6"+
    "\1\0\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6\1\7"+
    "\2\0\12\7\41\0\3\7\2\0\12\7\6\0\130\6\10\0\51\6"+
    "\1\7\1\6\5\0\106\6\12\0\35\6\3\0\14\7\4\0\14\7"+
    "\12\0\12\7\36\6\2\0\5\6\13\0\54\6\4\0\21\7\7\6"+
    "\2\7\6\0\12\7\46\0\27\6\5\7\4\0\65\6\12\7\1\0"+
    "\35\7\2\0\13\7\6\0\12\7\15\0\1\6\130\0\5\7\57\6"+
    "\21\7\7\6\4\0\12\7\21\0\11\7\14\0\3\7\36\6\12\7"+
    "\3\0\2\6\12\7\6\0\46\6\16\7\14\0\44\6\24\7\10\0"+
    "\12\7\3\0\3\6\12\7\44\6\122\0\3\7\1\0\25\7\4\6"+
    "\1\7\4\6\1\7\15\0\300\6\47\7\25\0\4\7\u0116\6\2\0"+
    "\6\6\2\0\46\6\2\0\6\6\2\0\10\6\1\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\37\6\2\0\65\6\1\0\7\6\1\0"+
    "\1\6\3\0\3\6\1\0\7\6\3\0\4\6\2\0\6\6\4\0"+
    "\15\6\5\0\3\6\1\0\7\6\16\0\5\7\32\0\5\7\20\0"+
    "\2\6\23\0\1\6\13\0\5\7\5\0\6\7\1\0\1\6\15\0"+
    "\1\6\20\0\15\6\3\0\32\6\26\0\15\7\4\0\1\7\3\0"+
    "\14\7\21\0\1\6\4\0\1\6\2\0\12\6\1\0\1\6\3\0"+
    "\5\6\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6\1\0"+
    "\13\6\2\0\4\6\5\0\5\6\4\0\1\6\21\0\51\6\u0a77\0"+
    "\57\6\1\0\57\6\1\0\205\6\6\0\4\6\3\7\16\0\46\6"+
    "\12\0\66\6\11\0\1\6\17\0\1\7\27\6\11\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\40\7\57\0\1\6\u01d5\0\3\6\31\0"+
    "\11\6\6\7\1\0\5\6\2\0\5\6\4\0\126\6\2\0\2\7"+
    "\2\0\3\6\1\0\132\6\1\0\4\6\5\0\51\6\3\0\136\6"+
    "\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cc\6\64\0\u048d\6"+
    "\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7\2\6\24\0\57\6"+
    "\1\7\14\0\2\7\1\0\31\6\10\0\120\6\2\7\45\0\11\6"+
    "\2\0\147\6\2\0\4\6\1\0\2\6\16\0\12\6\120\0\10\6"+
    "\1\7\3\6\1\7\4\6\1\7\27\6\5\7\20\0\1\6\7\0"+
    "\64\6\14\0\2\7\62\6\21\7\13\0\12\7\6\0\22\7\6\6"+
    "\3\0\1\6\4\0\12\7\34\6\10\7\2\0\27\6\15\7\14\0"+
    "\35\6\3\0\4\7\57\6\16\7\16\0\1\6\12\7\46\0\51\6"+
    "\16\7\11\0\3\6\1\7\10\6\2\7\2\0\12\7\6\0\27\6"+
    "\3\0\1\6\1\7\4\0\60\6\1\7\1\6\3\7\2\6\2\7"+
    "\5\6\2\7\1\6\1\7\1\6\30\0\3\6\43\0\6\6\2\0"+
    "\6\6\2\0\6\6\11\0\7\6\1\0\7\6\221\0\43\6\10\7"+
    "\1\0\2\7\2\0\12\7\6\0\u2ba4\6\14\0\27\6\4\0\61\6"+
    "\u2104\0\u012e\6\2\0\76\6\2\0\152\6\46\0\7\6\14\0\5\6"+
    "\5\0\1\6\1\7\12\6\1\0\15\6\1\0\5\6\1\0\1\6"+
    "\1\0\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0\100\6"+
    "\2\0\66\6\50\0\15\6\3\0\20\7\20\0\7\7\14\0\2\6"+
    "\30\0\3\6\31\0\1\6\6\0\5\6\1\0\207\6\2\0\1\7"+
    "\4\0\1\6\13\0\12\7\7\0\32\6\4\0\1\6\1\0\32\6"+
    "\13\0\131\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6"+
    "\3\0\2\6\3\0\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\1\2\3"+
    "\1\6\2\7\1\10\1\1\1\11\21\5\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\3"+
    "\1\23\1\24\2\25\1\1\1\26\1\2\1\3\1\0"+
    "\1\27\1\0\1\7\2\0\1\30\1\0\1\31\1\32"+
    "\1\33\1\30\1\34\1\0\2\35\1\0\10\5\1\34"+
    "\2\5\1\36\1\37\12\5\1\40\10\5\1\41\1\42"+
    "\1\3\1\43\1\44\1\45\2\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\0\1\3\1\56\1\57"+
    "\1\7\1\60\1\30\1\0\1\61\12\44\3\5\1\62"+
    "\4\5\1\63\4\5\1\64\1\65\3\5\1\66\3\5"+
    "\1\67\1\5\1\70\1\71\1\46\1\0\1\2\1\72"+
    "\1\73\1\0\1\74\1\0\1\75\1\76\1\77\1\100"+
    "\1\101\1\102\1\103\1\5\1\104\7\5\1\105\1\106"+
    "\1\107\14\5\1\110\3\5\1\111\5\5\1\112\2\5"+
    "\1\113\2\5\1\114\4\5\1\115\4\5\1\116\2\5"+
    "\1\117\3\5\1\120\1\5\1\121\1\122\4\5\1\123"+
    "\5\5\1\124\1\5\1\125\1\5\1\126\1\5\1\127"+
    "\1\130\4\5\1\131\1\5\1\132\1\133\1\5\1\134"+
    "\1\135\1\136";

  private static int [] zzUnpackAction() {
    int [] result = new int[267];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\172\0\267\0\364\0\u0131\0\u016e"+
    "\0\u01ab\0\u0131\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc\0\u0319"+
    "\0\172\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4"+
    "\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f\0\u06ac"+
    "\0\u06e9\0\u0726\0\u0763\0\172\0\172\0\172\0\172\0\172"+
    "\0\172\0\172\0\172\0\u07a0\0\u0131\0\u07dd\0\172\0\u081a"+
    "\0\u0857\0\172\0\u0894\0\u08d1\0\u01ab\0\172\0\u090e\0\u094b"+
    "\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\172\0\172\0\172\0\u0a7c"+
    "\0\172\0\u0ab9\0\172\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\u0bea"+
    "\0\u0c27\0\u0c64\0\u0ca1\0\u0cde\0\u0d1b\0\u016e\0\u0d58\0\u0d95"+
    "\0\u016e\0\u016e\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03"+
    "\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae\0\u10eb"+
    "\0\u1128\0\u1165\0\u11a2\0\u11df\0\u121c\0\172\0\172\0\u1259"+
    "\0\u0131\0\172\0\172\0\u1296\0\u12d3\0\172\0\172\0\172"+
    "\0\172\0\172\0\172\0\172\0\u1310\0\u134d\0\172\0\172"+
    "\0\u138a\0\u13c7\0\u1404\0\u1441\0\172\0\u147e\0\u14bb\0\u14f8"+
    "\0\u1535\0\u1572\0\u15af\0\u15ec\0\u1629\0\u1666\0\u16a3\0\u16e0"+
    "\0\u171d\0\u175a\0\u1797\0\u17d4\0\u1811\0\u184e\0\u188b\0\u016e"+
    "\0\u18c8\0\u1905\0\u1942\0\u197f\0\u016e\0\u016e\0\u19bc\0\u19f9"+
    "\0\u1a36\0\u1a73\0\u1ab0\0\u1aed\0\u1b2a\0\u016e\0\u1b67\0\u016e"+
    "\0\u0131\0\172\0\u1ba4\0\u0131\0\172\0\172\0\u14f8\0\172"+
    "\0\u1be1\0\172\0\172\0\172\0\172\0\172\0\172\0\172"+
    "\0\u1c1e\0\u016e\0\u1c5b\0\u1c98\0\u1cd5\0\u1d12\0\u1d4f\0\u1d8c"+
    "\0\u1dc9\0\u016e\0\u016e\0\u016e\0\u1e06\0\u1e43\0\u1e80\0\u1ebd"+
    "\0\u1efa\0\u1f37\0\u1f74\0\u1fb1\0\u1fee\0\u202b\0\u2068\0\u20a5"+
    "\0\u20e2\0\u211f\0\u215c\0\u2199\0\u016e\0\u21d6\0\u2213\0\u2250"+
    "\0\u228d\0\u22ca\0\u016e\0\u2307\0\u2344\0\u016e\0\u2381\0\u23be"+
    "\0\u016e\0\u23fb\0\u2438\0\u2475\0\u24b2\0\u016e\0\u24ef\0\u252c"+
    "\0\u2569\0\u25a6\0\u016e\0\u25e3\0\u2620\0\u016e\0\u265d\0\u269a"+
    "\0\u26d7\0\u016e\0\u2714\0\u016e\0\u016e\0\u2751\0\u278e\0\u27cb"+
    "\0\u2808\0\u016e\0\u2845\0\u2882\0\u28bf\0\u28fc\0\u2939\0\u016e"+
    "\0\u2976\0\u016e\0\u29b3\0\u016e\0\u29f0\0\u016e\0\u016e\0\u2a2d"+
    "\0\u2a6a\0\u2aa7\0\u2ae4\0\u016e\0\u2b21\0\u016e\0\u016e\0\u2b5e"+
    "\0\u016e\0\u016e\0\u016e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[267];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\4\1\6\1\7\1\10\1\3"+
    "\1\11\1\12\1\13\1\14\1\15\2\10\2\16\1\17"+
    "\1\10\1\12\1\20\1\21\1\16\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\10\1\30\1\31\1\10\1\32"+
    "\1\10\1\33\1\34\1\35\2\10\1\36\1\37\1\40"+
    "\1\41\1\42\3\10\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\2\10\1\56"+
    "\1\57\1\60\5\56\1\61\14\56\1\62\47\56\76\0"+
    "\1\4\77\0\1\63\1\64\3\0\3\12\7\0\1\12"+
    "\45\0\2\12\6\0\2\12\3\0\3\12\7\0\1\12"+
    "\45\0\2\12\10\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\32\10\13\0\2\10\10\65\1\66"+
    "\64\65\4\0\2\12\2\10\1\0\1\12\1\13\1\12"+
    "\5\10\1\0\1\10\1\12\2\0\32\10\11\0\2\12"+
    "\2\10\13\0\1\67\75\0\1\70\1\71\1\0\1\72"+
    "\1\70\1\73\1\74\3\0\1\70\1\0\1\74\13\0"+
    "\1\75\3\0\1\76\1\77\3\0\1\75\1\77\1\76"+
    "\14\0\1\71\14\0\1\16\2\0\2\16\1\73\1\74"+
    "\3\0\1\16\1\0\1\74\13\0\1\75\3\0\1\76"+
    "\1\77\3\0\1\75\1\77\1\76\31\0\1\100\2\0"+
    "\2\100\1\101\4\0\1\100\46\0\1\102\1\103\1\104"+
    "\5\102\1\105\13\102\1\0\50\102\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\2\10\1\106"+
    "\2\10\1\107\4\10\1\110\17\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\1\10\1\111\14\10\1\112\13\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\6\10\1\113\12\10\1\114\10\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\21\10\1\115\10\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\6\10\1\116"+
    "\7\10\1\117\13\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\1\10\1\120"+
    "\30\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\1\10\1\121\21\10\1\122"+
    "\1\123\5\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\3\10\1\124\26\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\5\10\1\125\13\10\1\126\10\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\1\10\1\127\14\10\1\130\13\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\2\10\1\131\12\10\1\132\14\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\2\10\1\133\5\10\1\134\21\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\5\10\1\135\2\10\1\136\21\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\5\10\1\137\4\10\1\140\2\10"+
    "\1\141\14\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\5\10\1\127\4\10"+
    "\1\142\2\10\1\143\14\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\6\10"+
    "\1\144\23\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\15\10\1\145\14\10"+
    "\13\0\2\10\13\0\1\146\44\0\1\147\20\0\2\12"+
    "\3\0\3\12\7\0\1\12\45\0\1\150\1\151\2\0"+
    "\1\56\2\0\5\56\1\0\14\56\1\0\47\56\1\0"+
    "\1\57\73\0\1\152\1\0\6\152\1\153\3\152\1\154"+
    "\3\152\1\155\3\152\1\156\1\157\1\154\1\160\1\152"+
    "\1\161\2\152\1\162\10\152\1\163\3\152\1\164\23\152"+
    "\1\63\1\4\1\5\72\63\4\165\1\64\1\166\3\165"+
    "\3\64\7\165\1\64\45\165\2\64\2\165\72\0\1\167"+
    "\16\0\1\70\2\0\1\72\1\70\1\100\1\74\3\0"+
    "\1\70\1\0\1\74\13\0\1\170\3\0\1\76\1\77"+
    "\3\0\1\170\1\77\1\76\31\0\1\171\1\0\3\171"+
    "\1\0\1\171\3\0\1\171\1\0\1\171\10\0\1\171"+
    "\1\0\1\171\1\0\1\171\2\0\2\171\4\0\2\171"+
    "\31\0\1\72\2\0\2\72\1\100\1\74\3\0\1\72"+
    "\1\0\1\74\17\0\1\76\1\77\4\0\1\77\1\76"+
    "\31\0\1\100\2\0\2\100\1\172\1\74\3\0\1\100"+
    "\1\0\1\74\17\0\1\76\1\77\4\0\1\77\1\76"+
    "\31\0\1\173\2\0\2\173\2\0\1\174\2\0\1\173"+
    "\42\0\1\174\17\0\1\100\2\0\2\100\1\0\1\74"+
    "\3\0\1\100\1\0\1\74\17\0\1\76\1\77\4\0"+
    "\1\77\1\76\41\0\1\175\51\0\1\103\73\0\1\152"+
    "\1\0\6\152\1\176\3\152\1\177\3\152\1\200\3\152"+
    "\1\201\1\202\1\177\1\203\1\152\1\204\2\152\1\205"+
    "\10\152\1\206\3\152\1\207\23\152\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\3\10\1\210"+
    "\26\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\3\10\1\116\26\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\16\10\1\211\13\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\3\10\1\212\16\10\1\213\7\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\11\10\1\214\20\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\12\10\1\215"+
    "\17\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\2\10\1\216\27\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\10\10\1\217\21\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\22\10\1\220\7\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\20\10\1\116"+
    "\11\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\25\10\1\221\4\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\6\10\1\222\23\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\1\10\1\223\30\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\5\10\1\224"+
    "\24\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\22\10\1\116\7\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\16\10\1\225\13\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\3\10\1\226\26\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\24\10\1\227"+
    "\5\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\20\10\1\230\11\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\3\10\1\231\26\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\24\10\1\116\5\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\26\10\1\116"+
    "\3\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\6\10\1\232\23\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\1\10\1\233\30\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\16\10\1\234\13\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\3\10\1\235"+
    "\26\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\25\10\1\236\4\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\5\10\1\237\24\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\6\10\1\240\23\10\13\0\2\10\4\0\2\12\3\0"+
    "\3\12\7\0\1\12\45\0\1\12\1\241\16\0\1\155"+
    "\3\0\1\155\5\0\1\155\62\0\1\242\3\0\1\242"+
    "\5\0\1\242\46\0\5\165\1\243\73\165\1\244\1\166"+
    "\3\165\3\64\7\165\1\64\45\165\2\64\2\165\14\0"+
    "\1\171\1\0\3\171\1\0\1\171\3\0\1\171\1\0"+
    "\1\171\10\0\1\171\1\0\1\171\1\170\1\171\2\0"+
    "\2\171\3\0\1\170\2\171\36\0\1\245\67\0\1\173"+
    "\2\0\2\173\5\0\1\173\21\0\1\76\1\77\4\0"+
    "\1\77\1\76\31\0\1\173\2\0\2\173\5\0\1\173"+
    "\72\0\1\246\64\0\1\247\3\0\1\247\3\0\1\250"+
    "\1\0\1\247\62\0\1\251\3\0\1\251\3\0\1\250"+
    "\1\0\1\251\72\0\1\252\74\0\1\253\74\0\1\254"+
    "\74\0\1\255\74\0\1\256\74\0\1\257\74\0\1\260"+
    "\56\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\4\10\1\261\25\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\16\10"+
    "\1\262\13\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\10\10\1\263\21\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\4\10\1\264\3\10\1\265\2\10"+
    "\1\266\2\10\1\267\4\10\1\270\1\10\1\271\4\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\2\10\1\272\27\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\2\10\1\273\27\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\1\10"+
    "\1\274\30\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\16\10\1\275\13\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\5\10\1\276\24\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\12\10\1\277\17\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\11\10"+
    "\1\300\20\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\5\10\1\301\24\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\17\10\1\302\12\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\10\10\1\303\21\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\32\10"+
    "\13\0\1\304\1\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\2\10\1\305\27\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\13\10\1\306\16\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\11\10\1\307\20\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\15\10\1\310"+
    "\14\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\13\10\1\311\16\10\13\0"+
    "\2\10\4\165\1\4\1\243\67\165\24\0\1\250\56\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\5\10\1\312\24\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\3\10\1\313"+
    "\26\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\21\10\1\314\10\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\23\10\1\315\6\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\21\10\1\316\10\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\2\10\1\317"+
    "\12\10\1\320\14\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\5\10\1\321"+
    "\24\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\6\10\1\322\23\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\2\10\1\323\27\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\6\10\1\324\23\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\13\10\1\325"+
    "\16\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\3\10\1\326\26\10\13\0"+
    "\2\10\6\0\2\10\2\0\1\10\1\0\5\10\1\0"+
    "\1\10\3\0\11\10\1\327\20\10\13\0\2\10\6\0"+
    "\2\10\2\0\1\10\1\0\5\10\1\0\1\10\3\0"+
    "\22\10\1\330\7\10\13\0\2\10\6\0\2\10\2\0"+
    "\1\10\1\0\5\10\1\0\1\10\3\0\1\10\1\331"+
    "\30\10\13\0\2\10\6\0\2\10\2\0\1\10\1\0"+
    "\5\10\1\0\1\10\3\0\5\10\1\332\24\10\13\0"+
    "\1\10\1\333\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\15\10\1\334\14\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\3\10\1\335\26\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\2\10"+
    "\1\336\27\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\17\10\1\337\12\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\2\10\1\340\27\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\6\10\1\341\23\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\10\10"+
    "\1\342\3\10\1\343\15\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\10\10"+
    "\1\344\21\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\5\10\1\345\24\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\3\10\1\346\26\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\24\10\1\347\5\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\6\10"+
    "\1\350\23\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\5\10\1\351\24\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\3\10\1\352\26\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\3\10\1\353\26\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\2\10"+
    "\1\354\27\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\15\10\1\355\14\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\6\10\1\116\23\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\5\10\1\332\24\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\13\10"+
    "\1\356\16\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\10\10\1\357\21\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\16\10\1\360\13\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\22\10\1\361\7\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\7\10"+
    "\1\362\22\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\2\10\1\363\27\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\16\10\1\364\13\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\5\10\1\365\24\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\17\10"+
    "\1\366\12\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\2\10\1\367\27\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\13\10\1\370\16\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\12\10\1\371\17\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\21\10"+
    "\1\372\10\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\5\10\1\373\24\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\2\10\1\374\27\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\12\10\1\375\17\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\11\10"+
    "\1\376\20\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\2\10\1\377\27\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\11\10\1\u0100\20\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\22\10\1\u0101\7\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\15\10"+
    "\1\u0102\14\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\6\10\1\u0103\23\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\1\10\1\u0104\30\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\6\10\1\u0105\23\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\2\10"+
    "\1\u0106\27\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\15\10\1\u0107\14\10"+
    "\13\0\2\10\6\0\2\10\2\0\1\10\1\0\5\10"+
    "\1\0\1\10\3\0\13\10\1\u0108\16\10\13\0\2\10"+
    "\6\0\2\10\2\0\1\10\1\0\5\10\1\0\1\10"+
    "\3\0\2\10\1\u0109\27\10\13\0\2\10\6\0\2\10"+
    "\2\0\1\10\1\0\5\10\1\0\1\10\3\0\2\10"+
    "\1\u010a\27\10\13\0\2\10\6\0\2\10\2\0\1\10"+
    "\1\0\5\10\1\0\1\10\3\0\21\10\1\u010b\10\10"+
    "\13\0\2\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11163];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\14\1\1\11\22\1\10\11\3\1\1\11"+
    "\2\1\1\11\2\1\1\0\1\11\1\0\1\1\2\0"+
    "\1\1\1\0\3\11\1\1\1\11\1\0\1\11\1\1"+
    "\1\0\40\1\2\11\2\1\2\11\2\1\7\11\1\0"+
    "\1\1\2\11\3\1\1\0\1\11\44\1\1\11\1\0"+
    "\1\1\2\11\1\0\1\11\1\0\7\11\133\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[267];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer strbuf = new StringBuffer(128);
  int sub_line;
  int sub_column;
  int strlit_start_line, strlit_start_column;

  private Symbol sym(short id) {
    return new Symbol(id, yyline + 1, yycolumn + 1, len(), str());
  }

  private Symbol sym(short id, String value) {
    return new Symbol(id, yyline + 1, yycolumn + 1, len(), value);
  }

  private Symbol sym(short id, String value, int start_line, int start_column, int len) {
    return new Symbol(id, start_line, start_column, len, value);
  }

  private String str() { return yytext(); }
  private int len() { return yylength(); }

  private void error(String msg) throws Scanner.Exception {
    throw new Scanner.Exception(yyline + 1, yycolumn + 1, msg);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public NlScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public NlScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2234) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 91: 
          { return sym(Terminals.ENDLAMBDA);
          }
        case 95: break;
        case 26: 
          { return sym(Terminals.DOUBLE_LITERAL, str().substring(0,len()-1));
          }
        case 96: break;
        case 93: 
          { return sym(Terminals.PROCEDURE);
          }
        case 97: break;
        case 77: 
          { return sym(Terminals.FALSE_LITERAL);
          }
        case 98: break;
        case 76: 
          { return sym(Terminals.BEGIN);
          }
        case 99: break;
        case 47: 
          { return sym(Terminals.LONG_LITERAL, str().substring(0, len()-1));
          }
        case 100: break;
        case 29: 
          { error("unterminated character literal at end of line");
          }
        case 101: break;
        case 59: 
          { return sym(Terminals.CHARACTER_LITERAL, "\\");
          }
        case 102: break;
        case 55: 
          { return sym(Terminals.MAP);
          }
        case 103: break;
        case 4: 
          { return sym(Terminals.MULT);
          }
        case 104: break;
        case 89: 
          { return sym(Terminals.FUNCTION);
          }
        case 105: break;
        case 35: 
          { return sym(Terminals.ARROW);
          }
        case 106: break;
        case 25: 
          { return sym(Terminals.LONG_LITERAL, str().substring(0,len()-1));
          }
        case 107: break;
        case 19: 
          { return sym(Terminals.GT);
          }
        case 108: break;
        case 21: 
          { error("unterminated string at end of line");
          }
        case 109: break;
        case 69: 
          { return sym(Terminals.ELSE);
          }
        case 110: break;
        case 6: 
          { return sym(Terminals.EQ);
          }
        case 111: break;
        case 78: 
          { return sym(Terminals.ENTITY);
          }
        case 112: break;
        case 42: 
          { strbuf.append( '\t' );
          }
        case 113: break;
        case 66: 
          { return sym(Terminals.CHARACTER_LITERAL, "\b");
          }
        case 114: break;
        case 20: 
          { strbuf.append(str());
          }
        case 115: break;
        case 75: 
          { return sym(Terminals.CONST);
          }
        case 116: break;
        case 12: 
          { return sym(Terminals.RPAREN);
          }
        case 117: break;
        case 32: 
          { return sym(Terminals.DO);
          }
        case 118: break;
        case 53: 
          { return sym(Terminals.LET);
          }
        case 119: break;
        case 48: 
          { yypushback(2); return sym(Terminals.INTEGER_LITERAL);
          }
        case 120: break;
        case 68: 
          { return sym(Terminals.NULL_LITERAL);
          }
        case 121: break;
        case 70: 
          { return sym(Terminals.TRUE_LITERAL);
          }
        case 122: break;
        case 50: 
          { return sym(Terminals.END);
          }
        case 123: break;
        case 56: 
          { return sym(Terminals.VAR);
          }
        case 124: break;
        case 60: 
          { int val = Integer.parseInt(str().substring(2,len()-1),8);
                                         return sym(Terminals.CHARACTER_LITERAL, new Character((char)val).toString());
          }
        case 125: break;
        case 3: 
          { // Some legal operator names are used in other parts of the language. Detect them.
                                   if(str().startsWith("->")){          // used by maps, "a->-b" is "a", "->", "-", "b"
                                     yypushback(str().length()-2);
                                     return sym(Terminals.ARROW, "->");
                                   }
                                   if("|".equals(str())){
                                     return sym(Terminals.BAR);
                                   }
                                   return sym(Terminals.OPERATOR);
          }
        case 126: break;
        case 67: 
          { return sym(Terminals.CHARACTER_LITERAL, "\f");
          }
        case 127: break;
        case 58: 
          { yypushback(2); return sym(Terminals.FLOATING_POINT_LITERAL);
          }
        case 128: break;
        case 41: 
          { strbuf.append( '\n' );
          }
        case 129: break;
        case 51: 
          { return sym(Terminals.OLD);
          }
        case 130: break;
        case 57: 
          { return sym(Terminals.EDGE);
          }
        case 131: break;
        case 82: 
          { return sym(Terminals.LAMBDA);
          }
        case 132: break;
        case 30: 
          { return sym(Terminals.IN);
          }
        case 133: break;
        case 38: 
          { strbuf.append((char)Integer.parseInt(str().substring(1),8));
          }
        case 134: break;
        case 94: 
          { return sym(Terminals.ENDFOREACH);
          }
        case 135: break;
        case 88: 
          { return sym(Terminals.ENDWHILE);
          }
        case 136: break;
        case 11: 
          { return sym(Terminals.LPAREN);
          }
        case 137: break;
        case 85: 
          { return sym(Terminals.FOREACH);
          }
        case 138: break;
        case 34: 
          { return sym(Terminals.DOUBLECOLON);
          }
        case 139: break;
        case 24: 
          { return sym(Terminals.DOUBLE_LITERAL);
          }
        case 140: break;
        case 28: 
          { return sym(Terminals.OPERATOR);
          }
        case 141: break;
        case 63: 
          { return sym(Terminals.CHARACTER_LITERAL, "\n");
          }
        case 142: break;
        case 87: 
          { return sym(Terminals.ENTITIES);
          }
        case 143: break;
        case 62: 
          { return sym(Terminals.CHARACTER_LITERAL, "\"");
          }
        case 144: break;
        case 17: 
          { return sym(Terminals.SEMICOLON);
          }
        case 145: break;
        case 16: 
          { return sym(Terminals.RBRACK);
          }
        case 146: break;
        case 36: 
          { error("illegal escape sequence \""+str()+"\"");
          }
        case 147: break;
        case 80: 
          { return sym(Terminals.IMPORT);
          }
        case 148: break;
        case 43: 
          { strbuf.append( '\r' );
          }
        case 149: break;
        case 44: 
          { strbuf.append( '\b' );
          }
        case 150: break;
        case 7: 
          { return sym(Terminals.INTEGER_LITERAL);
          }
        case 151: break;
        case 1: 
          { error("illegal character \""+str()+ "\"");
          }
        case 152: break;
        case 71: 
          { return sym(Terminals.THEN);
          }
        case 153: break;
        case 65: 
          { return sym(Terminals.CHARACTER_LITERAL, "\r");
          }
        case 154: break;
        case 31: 
          { return sym(Terminals.IF);
          }
        case 155: break;
        case 46: 
          { return sym(Terminals.PORTCONN);
          }
        case 156: break;
        case 90: 
          { return sym(Terminals.ENDCHOOSE);
          }
        case 157: break;
        case 83: 
          { return sym(Terminals.NETWORK);
          }
        case 158: break;
        case 40: 
          { strbuf.append( '\"' );
          }
        case 159: break;
        case 86: 
          { return sym(Terminals.MUTABLE);
          }
        case 160: break;
        case 61: 
          { return sym(Terminals.CHARACTER_LITERAL, "\'");
          }
        case 161: break;
        case 64: 
          { return sym(Terminals.CHARACTER_LITERAL, "\t");
          }
        case 162: break;
        case 10: 
          { return sym(Terminals.COLON);
          }
        case 163: break;
        case 54: 
          { return sym(Terminals.FOR);
          }
        case 164: break;
        case 39: 
          { strbuf.append( '\'' );
          }
        case 165: break;
        case 72: 
          { return sym(Terminals.PROC);
          }
        case 166: break;
        case 37: 
          { strbuf.append( '\\' );
          }
        case 167: break;
        case 23: 
          { return  sym(Terminals.IDENTIFIER, str().substring(1,len()-1));
          }
        case 168: break;
        case 14: 
          { return sym(Terminals.RBRACE);
          }
        case 169: break;
        case 52: 
          { return sym(Terminals.ALL);
          }
        case 170: break;
        case 73: 
          { return sym(Terminals.ENDIF);
          }
        case 171: break;
        case 49: 
          { return sym(Terminals.CHARACTER_LITERAL, str().substring(1, len()-1));
          }
        case 172: break;
        case 15: 
          { return sym(Terminals.LBRACK);
          }
        case 173: break;
        case 74: 
          { return sym(Terminals.WHILE);
          }
        case 174: break;
        case 45: 
          { strbuf.append( '\f' );
          }
        case 175: break;
        case 18: 
          { return sym(Terminals.COMMA);
          }
        case 176: break;
        case 79: 
          { return sym(Terminals.ENDLET);
          }
        case 177: break;
        case 92: 
          { return sym(Terminals.STRUCTURE);
          }
        case 178: break;
        case 5: 
          { return sym(Terminals.IDENTIFIER);
          }
        case 179: break;
        case 84: 
          { return sym(Terminals.ENDPROC);
          }
        case 180: break;
        case 9: 
          { yybegin(STRING); 
                                   // remember start position of string literal so we can
                                   // set its position correctly in the end
                                   strlit_start_line = yyline+1;
                                   strlit_start_column = yycolumn+1;
                                   strbuf.setLength(0);
          }
        case 181: break;
        case 13: 
          { return sym(Terminals.LBRACE);
          }
        case 182: break;
        case 22: 
          { yybegin(YYINITIAL); 
                                   return sym(Terminals.STRING_LITERAL, strbuf.toString(), strlit_start_line, strlit_start_column, strbuf.length()+2);
          }
        case 183: break;
        case 27: 
          { return sym(Terminals.FLOATING_POINT_LITERAL, str().substring(0,len()-1));
          }
        case 184: break;
        case 8: 
          { return sym(Terminals.DOT);
          }
        case 185: break;
        case 81: 
          { return sym(Terminals.CHOOSE);
          }
        case 186: break;
        case 2: 
          { 
          }
        case 187: break;
        case 33: 
          { return sym(Terminals.COLONEQ);
          }
        case 188: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return sym(Terminals.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
