package se.lth.cs.tycho.backend.c.test;

import se.lth.cs.tycho.backend.c.util.NetworkBuilder;
import se.lth.cs.tycho.instance.net.Network;

public class DecoderNetworkConstructor implements NetworkConstructor {

	@Override
	public Network constructNetwork(NodeReader reader) {
		NetworkBuilder builder = new NetworkBuilder();
		addPorts(builder);
		addNodes(builder, reader);
		addConnections(builder);
		return builder.build();
	}

	private void addPorts(NetworkBuilder builder) {
		builder.addInputPort("INPUT", Util.uintType(8));
		builder.addOutputPort("OUTPUT", Util.uintType(8));
	}

	private void addNodes(NetworkBuilder builder, NodeReader reader) {
		builder.addNode("decoder_serialize", reader.fromId("org.sc29.wg11.common.Algo_Byte2bit"));
		builder.addNode("decoder_Merger420", reader.fromId("org.sc29.wg11.common.Mgnt_Merger420"));
		builder.addNode("decoder_parser_parseheaders", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.parser.Algo_SynP"));
		builder.addNode("decoder_parser_mvseq", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.parser.Mgnt_MVSequence_LeftAndTopAndTopRight"));
		builder.addNode("decoder_parser_blkexp", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.parser.Mgnt_BlockExpand"));
		builder.addNode("decoder_parser_mvrecon", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.parser.Mgnt_MVR_MedianOfThreeLeftAndTopAndTopRight"));
		builder.addNode("decoder_parser_splitter_BTYPE", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.parser.Mgnt_Splitter_420_TYPE"));
		builder.addNode("decoder_parser_splitter_MV", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.parser.Mgnt_Splitter420MV"));
		builder.addNode("decoder_parser_splitter_420_B", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.parser.Mgnt_Splitter420B"));
		builder.addNode("decoder_texture_Y_DCsplit", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Mgnt_DCSplit"));
		builder.addNode("decoder_texture_Y_IS", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IS_ZigzagOrAlternateHorizontalVertical_8x8"));
		builder.addNode("decoder_texture_Y_IAP", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IAP_AdaptiveHorizontalOrVerticalPred_16x16"));
		builder.addNode("decoder_texture_Y_IQ", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IQ_QSAbdQmatrixMp4vOrH263Scaler"));
		builder.addNode("decoder_texture_Y_idct2d", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IDCT2D_ISOIEC_23002_1"));
		builder.addNode("decoder_texture_Y_DCRecontruction_addressing", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.dc_reconstruction.Algo_DCRAddr_ThreeLeftTop_16x16"));
		builder.addNode("decoder_texture_Y_DCRecontruction_invpred", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.dc_reconstruction.Algo_DCRInvPred_LUMA_16x16"));
		builder.addNode("decoder_texture_U_DCsplit", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Mgnt_DCSplit"));
		builder.addNode("decoder_texture_U_IS", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IS_ZigzagOrAlternateHorizontalVertical_8x8"));
		builder.addNode("decoder_texture_U_IAP", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IAP_AdaptiveHorizontalOrVerticalPred_8x8"));
		builder.addNode("decoder_texture_U_IQ", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IQ_QSAbdQmatrixMp4vOrH263Scaler"));
		builder.addNode("decoder_texture_U_idct2d", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IDCT2D_ISOIEC_23002_1"));
		builder.addNode("decoder_texture_U_DCRecontruction_addressing", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.dc_reconstruction.Algo_DCRAddr_ThreeLeftTop_8x8"));
		builder.addNode("decoder_texture_U_DCRecontruction_invpred", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.dc_reconstruction.Algo_DCRInvPred_CHROMA_8x8"));
		builder.addNode("decoder_texture_V_DCsplit", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Mgnt_DCSplit"));
		builder.addNode("decoder_texture_V_IS", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IS_ZigzagOrAlternateHorizontalVertical_8x8"));
		builder.addNode("decoder_texture_V_IAP", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IAP_AdaptiveHorizontalOrVerticalPred_8x8"));
		builder.addNode("decoder_texture_V_IQ", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IQ_QSAbdQmatrixMp4vOrH263Scaler"));
		builder.addNode("decoder_texture_V_idct2d", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.Algo_IDCT2D_ISOIEC_23002_1"));
		builder.addNode("decoder_texture_V_DCRecontruction_addressing", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.dc_reconstruction.Algo_DCRAddr_ThreeLeftTop_8x8"));
		builder.addNode("decoder_texture_V_DCRecontruction_invpred", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.texture.dc_reconstruction.Algo_DCRInvPred_CHROMA_8x8"));
		builder.addNode("decoder_motion_Y_interpolation", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Algo_Interp_HalfpelBilinearRoundingControl"));
		builder.addNode("decoder_motion_Y_add", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Algo_PictureReconstruction_Saturation"));
		builder.addNode("decoder_motion_Y_FrameBuff", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Mgnt_FB_w_Address_16X16"));
		builder.addNode("decoder_motion_U_interpolation", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Algo_Interp_HalfpelBilinearRoundingControl"));
		builder.addNode("decoder_motion_U_add", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Algo_PictureReconstruction_Saturation"));
		builder.addNode("decoder_motion_U_FrameBuff", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Mgnt_FB_w_Address_8X8"));
		builder.addNode("decoder_motion_V_interpolation", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Algo_Interp_HalfpelBilinearRoundingControl"));
		builder.addNode("decoder_motion_V_add", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Algo_PictureReconstruction_Saturation"));
		builder.addNode("decoder_motion_V_FrameBuff", reader.fromId("org.sc29.wg11.mpeg4.part2.sp.motion.Mgnt_FB_w_Address_8X8"));
	}

	private void addConnections(NetworkBuilder builder) {
		builder.addConnection("decoder_parser_parseheaders", "MV", "decoder_parser_mvrecon", "MVIN");
		builder.addConnection("decoder_parser_parseheaders", "RUN", "decoder_parser_blkexp", "RUN");
		builder.addConnection("decoder_parser_parseheaders", "VALUE", "decoder_parser_blkexp", "VALUE");
		builder.addConnection("decoder_parser_parseheaders", "LAST", "decoder_parser_blkexp", "LAST");
		builder.addConnection("decoder_parser_mvseq", "A", "decoder_parser_mvrecon", "A");
		builder.addConnection("decoder_parser_blkexp", "OUT", "decoder_parser_splitter_420_B", "B");
		builder.addConnection("decoder_parser_mvrecon", "MV", "decoder_parser_splitter_MV", "MV");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_parser_mvrecon", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_parser_mvseq", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "FCODE", "decoder_parser_mvrecon", "FCODE");
		builder.addConnection("decoder_parser_parseheaders", "ACCODED", "decoder_parser_splitter_420_B", "ACCODED");
		builder.addConnection("decoder_parser_parseheaders", "ACCODED", "decoder_parser_splitter_BTYPE", "ACCODED");
		builder.addConnection("decoder_parser_parseheaders", "MOTION", "decoder_parser_mvseq", "MOTION");
		builder.addConnection("decoder_parser_parseheaders", "MOTION", "decoder_parser_splitter_MV", "MOTION");
		builder.addConnection("decoder_parser_parseheaders", "MOTION", "decoder_parser_mvrecon", "MOTION");
		builder.addConnection("decoder_parser_parseheaders", "MOTION", "decoder_parser_splitter_BTYPE", "MOTION");
		builder.addConnection("decoder_parser_parseheaders", "ACPRED", "decoder_parser_splitter_BTYPE", "ACPRED");
		builder.addConnection("decoder_parser_parseheaders", "FOUR_MV", "decoder_parser_mvseq", "FOUR_MV");
		builder.addConnection("decoder_parser_parseheaders", "FOUR_MV", "decoder_parser_mvrecon", "FOUR_MV");
		builder.addConnection("decoder_parser_parseheaders", "BTYPE", "decoder_parser_splitter_BTYPE", "BTYPE");
		builder.addConnection("decoder_parser_parseheaders", "BTYPE", "decoder_parser_mvseq", "BTYPE");
		builder.addConnection("decoder_parser_parseheaders", "BTYPE", "decoder_parser_splitter_420_B", "BTYPE");
		builder.addConnection("decoder_parser_parseheaders", "BTYPE", "decoder_parser_mvrecon", "BTYPE");
		builder.addConnection("decoder_parser_parseheaders", "QP", "decoder_parser_splitter_BTYPE", "QP");
		builder.addConnection("decoder_serialize", "BITS", "decoder_parser_parseheaders", "BITS");
		builder.addConnection("decoder_texture_Y_DCsplit", "AC", "decoder_texture_Y_IS", "QFS_AC");
		builder.addConnection("decoder_texture_Y_IS", "PQF_AC", "decoder_texture_Y_IAP", "PQF_AC");
		builder.addConnection("decoder_texture_Y_IAP", "QF_AC", "decoder_texture_Y_IQ", "AC");
		builder.addConnection("decoder_texture_Y_IQ", "OUT", "decoder_texture_Y_idct2d", "IN");
		builder.addConnection("decoder_texture_Y_DCRecontruction_addressing", "A", "decoder_texture_Y_DCRecontruction_invpred", "A");
		builder.addConnection("decoder_texture_Y_DCRecontruction_addressing", "B", "decoder_texture_Y_DCRecontruction_invpred", "B");
		builder.addConnection("decoder_texture_Y_DCRecontruction_addressing", "C", "decoder_texture_Y_DCRecontruction_invpred", "C");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "QUANT", "decoder_texture_Y_IQ", "QP");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "QF_DC", "decoder_texture_Y_IQ", "DC");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "PTR", "decoder_texture_Y_IAP", "PTR");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "AC_PRED_DIR", "decoder_texture_Y_IAP", "AC_PRED_DIR");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "AC_PRED_DIR", "decoder_texture_Y_IS", "AC_PRED_DIR");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "SIGNED", "decoder_texture_Y_idct2d", "SIGNED");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "QUANT", "decoder_texture_Y_IAP", "QP");
		builder.addConnection("decoder_texture_Y_DCRecontruction_invpred", "PREV_QUANT", "decoder_texture_Y_IAP", "PREV_QP");
		builder.addConnection("decoder_texture_Y_DCsplit", "DC", "decoder_texture_Y_DCRecontruction_invpred", "QFS_DC");
		builder.addConnection("decoder_parser_splitter_420_B", "B_Y", "decoder_texture_Y_DCsplit", "IN");
		builder.addConnection("decoder_parser_splitter_BTYPE", "QP_Y", "decoder_texture_Y_DCRecontruction_invpred", "QP");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_texture_Y_DCRecontruction_addressing", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_texture_Y_DCRecontruction_invpred", "WIDTH");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACCODED_Y", "decoder_texture_Y_DCRecontruction_invpred", "AC_CODED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACPRED_Y", "decoder_texture_Y_DCRecontruction_invpred", "AC_PRED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_Y", "decoder_texture_Y_DCRecontruction_addressing", "BTYPE");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_Y", "decoder_texture_Y_DCRecontruction_invpred", "BTYPE");
		builder.addConnection("decoder_texture_U_DCsplit", "AC", "decoder_texture_U_IS", "QFS_AC");
		builder.addConnection("decoder_texture_U_IS", "PQF_AC", "decoder_texture_U_IAP", "PQF_AC");
		builder.addConnection("decoder_texture_U_IAP", "QF_AC", "decoder_texture_U_IQ", "AC");
		builder.addConnection("decoder_texture_U_IQ", "OUT", "decoder_texture_U_idct2d", "IN");
		builder.addConnection("decoder_texture_U_DCRecontruction_addressing", "A", "decoder_texture_U_DCRecontruction_invpred", "A");
		builder.addConnection("decoder_texture_U_DCRecontruction_addressing", "B", "decoder_texture_U_DCRecontruction_invpred", "B");
		builder.addConnection("decoder_texture_U_DCRecontruction_addressing", "C", "decoder_texture_U_DCRecontruction_invpred", "C");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "SIGNED", "decoder_texture_U_idct2d", "SIGNED");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "QUANT", "decoder_texture_U_IQ", "QP");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "QF_DC", "decoder_texture_U_IQ", "DC");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "PTR", "decoder_texture_U_IAP", "PTR");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "AC_PRED_DIR", "decoder_texture_U_IAP", "AC_PRED_DIR");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "AC_PRED_DIR", "decoder_texture_U_IS", "AC_PRED_DIR");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "QUANT", "decoder_texture_U_IAP", "QP");
		builder.addConnection("decoder_texture_U_DCRecontruction_invpred", "PREV_QUANT", "decoder_texture_U_IAP", "PREV_QP");
		builder.addConnection("decoder_texture_U_DCsplit", "DC", "decoder_texture_U_DCRecontruction_invpred", "QFS_DC");
		builder.addConnection("decoder_parser_splitter_420_B", "B_U", "decoder_texture_U_DCsplit", "IN");
		builder.addConnection("decoder_parser_splitter_BTYPE", "QP_U", "decoder_texture_U_DCRecontruction_invpred", "QP");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_texture_U_DCRecontruction_addressing", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_texture_U_DCRecontruction_invpred", "WIDTH");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACCODED_U", "decoder_texture_U_DCRecontruction_invpred", "AC_CODED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACPRED_U", "decoder_texture_U_DCRecontruction_invpred", "AC_PRED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_U", "decoder_texture_U_DCRecontruction_addressing", "BTYPE");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_U", "decoder_texture_U_DCRecontruction_invpred", "BTYPE");
		builder.addConnection("decoder_texture_V_DCsplit", "AC", "decoder_texture_V_IS", "QFS_AC");
		builder.addConnection("decoder_texture_V_IS", "PQF_AC", "decoder_texture_V_IAP", "PQF_AC");
		builder.addConnection("decoder_texture_V_IAP", "QF_AC", "decoder_texture_V_IQ", "AC");
		builder.addConnection("decoder_texture_V_IQ", "OUT", "decoder_texture_V_idct2d", "IN");
		builder.addConnection("decoder_texture_V_DCRecontruction_addressing", "A", "decoder_texture_V_DCRecontruction_invpred", "A");
		builder.addConnection("decoder_texture_V_DCRecontruction_addressing", "B", "decoder_texture_V_DCRecontruction_invpred", "B");
		builder.addConnection("decoder_texture_V_DCRecontruction_addressing", "C", "decoder_texture_V_DCRecontruction_invpred", "C");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "SIGNED", "decoder_texture_V_idct2d", "SIGNED");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "QUANT", "decoder_texture_V_IQ", "QP");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "QF_DC", "decoder_texture_V_IQ", "DC");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "PTR", "decoder_texture_V_IAP", "PTR");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "AC_PRED_DIR", "decoder_texture_V_IAP", "AC_PRED_DIR");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "AC_PRED_DIR", "decoder_texture_V_IS", "AC_PRED_DIR");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "QUANT", "decoder_texture_V_IAP", "QP");
		builder.addConnection("decoder_texture_V_DCRecontruction_invpred", "PREV_QUANT", "decoder_texture_V_IAP", "PREV_QP");
		builder.addConnection("decoder_texture_V_DCsplit", "DC", "decoder_texture_V_DCRecontruction_invpred", "QFS_DC");
		builder.addConnection("decoder_parser_splitter_420_B", "B_V", "decoder_texture_V_DCsplit", "IN");
		builder.addConnection("decoder_parser_splitter_BTYPE", "QP_V", "decoder_texture_V_DCRecontruction_invpred", "QP");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_texture_V_DCRecontruction_addressing", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_texture_V_DCRecontruction_invpred", "WIDTH");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACCODED_V", "decoder_texture_V_DCRecontruction_invpred", "AC_CODED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACPRED_V", "decoder_texture_V_DCRecontruction_invpred", "AC_PRED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_V", "decoder_texture_V_DCRecontruction_addressing", "BTYPE");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_V", "decoder_texture_V_DCRecontruction_invpred", "BTYPE");
		builder.addConnection("decoder_motion_Y_interpolation", "MOT", "decoder_motion_Y_add", "MOT");
		builder.addConnection("decoder_motion_Y_FrameBuff", "RD", "decoder_motion_Y_interpolation", "RD");
		builder.addConnection("decoder_motion_Y_FrameBuff", "halfpel", "decoder_motion_Y_interpolation", "halfpel");
		builder.addConnection("decoder_motion_Y_add", "VID", "decoder_motion_Y_FrameBuff", "WD");
		builder.addConnection("decoder_motion_Y_add", "VID", "decoder_Merger420", "Y");
		builder.addConnection("decoder_parser_splitter_MV", "MV_Y", "decoder_motion_Y_FrameBuff", "MV");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_motion_Y_FrameBuff", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "HEIGHT", "decoder_motion_Y_FrameBuff", "HEIGHT");
		builder.addConnection("decoder_parser_parseheaders", "ROUND", "decoder_motion_Y_FrameBuff", "ROUND");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACCODED_Y", "decoder_motion_Y_add", "ACCODED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "MOTION_Y", "decoder_motion_Y_FrameBuff", "MOT");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_Y", "decoder_motion_Y_add", "BTYPE");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_Y", "decoder_motion_Y_FrameBuff", "BTYPE");
		builder.addConnection("decoder_texture_Y_idct2d", "OUT", "decoder_motion_Y_add", "TEX");
		builder.addConnection("decoder_motion_U_interpolation", "MOT", "decoder_motion_U_add", "MOT");
		builder.addConnection("decoder_motion_U_FrameBuff", "RD", "decoder_motion_U_interpolation", "RD");
		builder.addConnection("decoder_motion_U_FrameBuff", "halfpel", "decoder_motion_U_interpolation", "halfpel");
		builder.addConnection("decoder_motion_U_add", "VID", "decoder_motion_U_FrameBuff", "WD");
		builder.addConnection("decoder_motion_U_add", "VID", "decoder_Merger420", "U");
		builder.addConnection("decoder_parser_splitter_MV", "MV_U", "decoder_motion_U_FrameBuff", "MV");
		builder.addConnection("decoder_parser_parseheaders", "HEIGHT", "decoder_motion_U_FrameBuff", "HEIGHT");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_motion_U_FrameBuff", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "ROUND", "decoder_motion_U_FrameBuff", "ROUND");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACCODED_U", "decoder_motion_U_add", "ACCODED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "MOTION_U", "decoder_motion_U_FrameBuff", "MOT");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_U", "decoder_motion_U_add", "BTYPE");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_U", "decoder_motion_U_FrameBuff", "BTYPE");
		builder.addConnection("decoder_texture_U_idct2d", "OUT", "decoder_motion_U_add", "TEX");
		builder.addConnection("decoder_motion_V_interpolation", "MOT", "decoder_motion_V_add", "MOT");
		builder.addConnection("decoder_motion_V_FrameBuff", "RD", "decoder_motion_V_interpolation", "RD");
		builder.addConnection("decoder_motion_V_FrameBuff", "halfpel", "decoder_motion_V_interpolation", "halfpel");
		builder.addConnection("decoder_motion_V_add", "VID", "decoder_motion_V_FrameBuff", "WD");
		builder.addConnection("decoder_motion_V_add", "VID", "decoder_Merger420", "V");
		builder.addConnection("decoder_parser_splitter_MV", "MV_V", "decoder_motion_V_FrameBuff", "MV");
		builder.addConnection("decoder_parser_parseheaders", "WIDTH", "decoder_motion_V_FrameBuff", "WIDTH");
		builder.addConnection("decoder_parser_parseheaders", "HEIGHT", "decoder_motion_V_FrameBuff", "HEIGHT");
		builder.addConnection("decoder_parser_parseheaders", "ROUND", "decoder_motion_V_FrameBuff", "ROUND");
		builder.addConnection("decoder_parser_splitter_BTYPE", "ACCODED_V", "decoder_motion_V_add", "ACCODED");
		builder.addConnection("decoder_parser_splitter_BTYPE", "MOTION_V", "decoder_motion_V_FrameBuff", "MOT");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_V", "decoder_motion_V_add", "BTYPE");
		builder.addConnection("decoder_parser_splitter_BTYPE", "BTYPE_V", "decoder_motion_V_FrameBuff", "BTYPE");
		builder.addConnection("decoder_texture_V_idct2d", "OUT", "decoder_motion_V_add", "TEX");
		builder.addConnection("decoder_Merger420", "YUV", null, "OUTPUT");
		builder.addConnection(null, "INPUT", "decoder_serialize", "BYTE");
	}
}
